import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import type { RegistryConfig, ParsedEntry, GenerateResult } from './types.js';

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function computeHash(entries: ParsedEntry[]): string {
  const hash = createHash('sha256');
  for (const entry of entries) {
    const content = readFileSync(entry.filePath, 'utf-8');
    hash.update(entry.filePath + '\n' + content);
  }
  return hash.digest('hex').slice(0, 16);
}

export function generateRegistry(
  name: string,
  config: RegistryConfig,
  entries: ParsedEntry[],
  outputPath: string
): GenerateResult {
  const idType = config.types?.id ?? `${capitalize(name)}Id`;
  const entryType = config.types?.entry ?? `${capitalize(name)}Entry`;
  const metaType = config.types?.meta ?? `${capitalize(name)}Meta`;
  
  const singular = name.replace(/s$/, '');
  const capitalSingular = capitalize(singular);
  
  const hash = computeHash(entries);
  const idUnion = entries.map(e => `"${e.id}"`).join(' | ') || 'never';

  const metaImports = entries
    .map((e, i) => `import { metadata as meta_${i} } from "${e.importPath}";`)
    .join('\n');

  const registryEntries = entries
    .map((e, i) => `  { id: "${e.id}" as const, href: "${e.href}", meta: meta_${i} },`)
    .join('\n');

  const loaderEntries = entries
    .map(e => `  "${e.id}": () => import("${e.importPath}"),`)
    .join('\n');

  const lazyEntries = entries
    .map(e => `  "${e.id}": lazy(loaders["${e.id}"]),`)
    .join('\n');

  const typeImports = config.typeImports ?? 
    `import type { ${entryType}, ${metaType}, LazyComponent } from "../types";`;

  const code = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by reggie
// @generated-hash: ${hash}

import { lazy, type ComponentType } from "react";
${typeImports}

${metaImports}

export type ${idType} = ${idUnion};

export const ${name.toUpperCase()}: ReadonlyArray<${entryType} & { id: ${idType} }> = [
${registryEntries}
];

export const ${name.toUpperCase()}_BY_ID = Object.fromEntries(
  ${name.toUpperCase()}.map(entry => [entry.id, entry])
) as Record<${idType}, ${entryType} & { id: ${idType} }>;

const loaders: Record<${idType}, () => Promise<{ default: ComponentType<unknown> }>> = {
${loaderEntries}
};

const lazyComponents: Record<${idType}, LazyComponent> = {
${lazyEntries}
};

export function get${capitalSingular}Component(id: ${idType}): LazyComponent {
  const component = lazyComponents[id];
  if (!component) {
    throw new Error(\`Unknown ${singular} id: \${id}. Available: \${Object.keys(lazyComponents).join(", ")}\`);
  }
  return component;
}

export async function load${capitalSingular}(id: ${idType}): Promise<ComponentType<unknown>> {
  const loader = loaders[id];
  if (!loader) {
    throw new Error(\`Unknown ${singular} id: \${id}\`);
  }
  const module = await loader();
  return module.default;
}
`;

  return {
    name,
    outputPath,
    entryCount: entries.length,
    code,
    hash,
  };
}
