import type { Source } from "../types/sources.js";
import { SPDX_LICENSE } from "../types/sources.js";

export interface AttributionOptions {
	includeUrl?: boolean;
	format?: "text" | "html";
}

export function generateAttribution(
	source: Source,
	options: AttributionOptions = {},
): string {
	const { includeUrl = true, format = "text" } = options;

	if (format === "html") {
		return generateHtmlAttribution(source, includeUrl);
	}

	return source.attributionTemplate;
}

function generateHtmlAttribution(source: Source, includeUrl: boolean): string {
	const license = source.license;

	if (license === SPDX_LICENSE.CC0_1_0) {
		return includeUrl
			? `Data from <a href="${source.url}">${source.name}</a> - <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Public Domain</a>`
			: `Data from ${source.name} - CC0 1.0 Public Domain`;
	}

	if (license === SPDX_LICENSE.CC_BY_4_0) {
		return includeUrl
			? `Data from <a href="${source.url}">${source.name}</a> licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>`
			: `Data from ${source.name} licensed under CC BY 4.0`;
	}

	if (license === SPDX_LICENSE.CC_BY_SA_4_0) {
		return includeUrl
			? `Content from <a href="${source.url}">${source.name}</a> licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>`
			: `Content from ${source.name} licensed under CC BY-SA 4.0`;
	}

	if (license === SPDX_LICENSE.PUBLIC_DOMAIN) {
		return includeUrl
			? `Data from <a href="${source.url}">${source.name}</a> - Public Domain`
			: `Data from ${source.name} - Public Domain`;
	}

	if (license === SPDX_LICENSE.PROPRIETARY_AI) {
		return includeUrl
			? `Generated by <a href="${source.url}">Slopcade AI</a>`
			: "Generated by Slopcade AI";
	}

	return source.attributionTemplate;
}

export function generateBulkAttribution(sources: Source[]): string {
	const attributions = sources.map((source) => generateAttribution(source));
	return attributions.join("\n");
}

export function generateBulkAttributionHtml(sources: Source[]): string {
	const attributions = sources.map((source) =>
		generateAttribution(source, { format: "html" }),
	);
	return `<ul>${attributions.map((attr) => `<li>${attr}</li>`).join("")}</ul>`;
}
