import { type Source, SPDX_LICENSE } from "../types/sources.js";

export const APPROVED_SOURCES: Record<string, Source> = {
	opentdb: {
		id: "opentdb",
		name: "Open Trivia Database",
		url: "https://opentdb.com",
		license: SPDX_LICENSE.CC_BY_SA_4_0,
		description: "Community-maintained trivia questions database",
		attributionTemplate:
			"Questions from Open Trivia Database (https://opentdb.com) licensed under CC BY-SA 4.0",
	},
	wikidata: {
		id: "wikidata",
		name: "Wikidata",
		url: "https://www.wikidata.org",
		license: SPDX_LICENSE.CC0_1_0,
		description: "Free and open knowledge base",
		attributionTemplate:
			"Data from Wikidata (https://www.wikidata.org) - CC0 1.0 Public Domain",
	},
	wikipedia_unusual: {
		id: "wikipedia_unusual",
		name: "Wikipedia Unusual Articles",
		url: "https://en.wikipedia.org/wiki/Wikipedia:Unusual_articles",
		license: SPDX_LICENSE.CC_BY_SA_4_0,
		description: "Curated list of unusual Wikipedia articles",
		attributionTemplate:
			"Content from Wikipedia (https://en.wikipedia.org) licensed under CC BY-SA 4.0",
	},
	world_bank: {
		id: "world_bank",
		name: "World Bank Open Data",
		url: "https://data.worldbank.org",
		license: SPDX_LICENSE.CC_BY_4_0,
		description: "Global development data and statistics",
		attributionTemplate:
			"Data from World Bank Open Data (https://data.worldbank.org) licensed under CC BY 4.0",
	},
	gapminder: {
		id: "gapminder",
		name: "Gapminder",
		url: "https://www.gapminder.org",
		license: SPDX_LICENSE.CC_BY_4_0,
		description: "Global statistics and trends",
		attributionTemplate:
			"Data from Gapminder (https://www.gapminder.org) licensed under CC BY 4.0",
	},
	cia_factbook: {
		id: "cia_factbook",
		name: "CIA World Factbook",
		url: "https://www.cia.gov/the-world-factbook",
		license: SPDX_LICENSE.PUBLIC_DOMAIN,
		description: "Country profiles and statistics",
		attributionTemplate:
			"Data from CIA World Factbook (https://www.cia.gov/the-world-factbook) - Public Domain",
	},
	us_gov_data: {
		id: "us_gov_data",
		name: "US Government Open Data",
		url: "https://data.gov",
		license: SPDX_LICENSE.PUBLIC_DOMAIN,
		description: "US federal government datasets",
		attributionTemplate:
			"Data from Data.gov (https://data.gov) - Public Domain",
	},
	ai_generated: {
		id: "ai_generated",
		name: "AI Generated Content",
		url: "https://slopcade.com",
		license: SPDX_LICENSE.PROPRIETARY_AI,
		description: "Content generated by Slopcade AI systems",
		attributionTemplate: "Generated by Slopcade AI",
	},
};

export function getSource(id: string): Source | undefined {
	return APPROVED_SOURCES[id];
}

export function listSources(): Source[] {
	return Object.values(APPROVED_SOURCES);
}
