packages:
  - 'api'
  - 'apps/admin'
  - 'apps/slopcade'
  - 'apps/amen'
  - 'apps/slopbox'
  - 'apps/shader-editor'
  - 'apps/landing-slopcade'
  - 'apps/landing-amen'
  - 'shared'
  - 'packages/*'
  - 'apps/storybook'

nodeLinker: hoisted
