packages:
  - 'api'
  - 'apps/admin'
  - 'apps/slopcade'
  - 'apps/amen'
  - 'apps/slopbox'
  - 'apps/shader-editor'
  - 'apps/pencil'
  - 'apps/landing-slopcade'
  - 'apps/landing-amen'
  - 'shared'
  - 'packages/*'
  - '!packages/design-canvas'
  - '!packages/pencil-core'
  - '!packages/pencil-server'
  - '!packages/protocol'
  - 'apps/storybook'

nodeLinker: hoisted
