import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const BEAM_WIDTH = 8;
const BEAM_HEIGHT = 0.3;
const PIVOT_SIZE = 0.6;
const WEIGHT_RADIUS = 0.4;

export const tipScaleConfig: GameAssetConfig = {
  gameId: 'tipScale',
  gameTitle: 'Tip the Scale',
  theme: 'Victorian steampunk workshop, brass gears, copper pipes, industrial elegance',
  style: 'cartoon',
  r2Prefix: 'generated/tipScale',
  assets: [
    {
      type: 'entity',
      id: 'beam',
      shape: 'box',
      width: BEAM_WIDTH,
      height: BEAM_HEIGHT,
      entityType: 'platform',
      description: 'a polished wooden plank with ornate brass fittings on the ends, Victorian steampunk seesaw beam with copper rivets and decorative metal trim, rich mahogany wood with golden brass accents',
      color: '#8D6E63',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'beamSensor',
      shape: 'box',
      width: BEAM_WIDTH,
      height: 0.6,
      entityType: 'platform',
      description: 'a subtle translucent placement guide area above the beam, faint steampunk grid pattern, semi-transparent with brass-tinted edges',
      color: '#00000022',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'pivot',
      shape: 'box',
      width: PIVOT_SIZE,
      height: PIVOT_SIZE,
      entityType: 'platform',
      description: 'an ornate brass gear mechanism serving as a fulcrum, Victorian steampunk pivot point with interlocking cogs and copper details, polished golden brass with industrial elegance',
      color: '#546E7A',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'weightChoice0',
      shape: 'circle',
      width: WEIGHT_RADIUS * 2,
      height: WEIGHT_RADIUS * 2,
      entityType: 'item',
      description: 'a small brass sphere weight with embossed gear patterns, Victorian steampunk counterweight with polished copper surface and decorative rivets, warm golden brass color',
      color: '#4CAF50',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'weightChoice1',
      shape: 'circle',
      width: WEIGHT_RADIUS * 1.3 * 2,
      height: WEIGHT_RADIUS * 1.3 * 2,
      entityType: 'item',
      description: 'a medium brass sphere weight with intricate clockwork engravings, Victorian steampunk counterweight with copper patina and gear motifs, polished bronze color',
      color: '#2196F3',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'weightChoice2',
      shape: 'circle',
      width: WEIGHT_RADIUS * 1.6 * 2,
      height: WEIGHT_RADIUS * 1.6 * 2,
      entityType: 'item',
      description: 'a large brass sphere weight with elaborate steampunk machinery details, Victorian industrial counterweight with copper pipes and pressure gauges, rich copper-brass color',
      color: '#FF9800',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedWeight0',
      shape: 'circle',
      width: WEIGHT_RADIUS * 2,
      height: WEIGHT_RADIUS * 2,
      entityType: 'item',
      description: 'a small brass sphere weight resting on the beam with embossed gear patterns, Victorian steampunk counterweight with polished copper surface, warm golden brass color',
      color: '#4CAF50',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedWeight1',
      shape: 'circle',
      width: WEIGHT_RADIUS * 1.3 * 2,
      height: WEIGHT_RADIUS * 1.3 * 2,
      entityType: 'item',
      description: 'a medium brass sphere weight resting on the beam with clockwork engravings, Victorian steampunk counterweight with copper patina, polished bronze color',
      color: '#2196F3',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedWeight2',
      shape: 'circle',
      width: WEIGHT_RADIUS * 1.6 * 2,
      height: WEIGHT_RADIUS * 1.6 * 2,
      entityType: 'item',
      description: 'a large brass sphere weight resting on the beam with steampunk machinery details, Victorian industrial counterweight with copper pipes, rich copper-brass color',
      color: '#FF9800',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A Victorian steampunk workshop interior for a puzzle game. Walls lined with brass pipes, copper tubing, and pressure gauges. Large ornate gears and clockwork mechanisms visible in the background. Warm amber lighting from gas lamps and glowing furnaces. Wooden workbenches with brass instruments and tools. Industrial elegance with rich browns, golden brass, and copper tones. Steam wisps and mechanical atmosphere.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Tip the Scale',
      themeDescription: 'Victorian steampunk aesthetic with brass and copper metallic letters, gear and cog decorations, industrial elegance, warm amber glow effects, clockwork mechanical accents',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
