// AUTO-GENERATED - DO NOT EDIT
// Generated by api/scripts/build-games.ts

export const EMBEDDED_MANIFEST = require('@/assets/embedded-games/manifest.json');

export const EMBEDDED_DEFINITIONS: Record<string, unknown> = {
  'ballSort': require('@/assets/embedded-games/ballSort/definition.json'),
  'breakoutBouncer': require('@/assets/embedded-games/breakoutBouncer/definition.json'),
  'flappyBird': require('@/assets/embedded-games/flappyBird/definition.json'),
  'gemCrush': require('@/assets/embedded-games/gemCrush/definition.json'),
  'headsUp': require('@/assets/embedded-games/headsUp/definition.json'),
  'kishimisuSwirl': require('@/assets/embedded-games/kishimisuSwirl/definition.json'),
  'minefield': require('@/assets/embedded-games/minefield/definition.json'),
  'mrPotatoHead': require('@/assets/embedded-games/mrPotatoHead/definition.json'),
  'shaderCRT': require('@/assets/embedded-games/shaderCRT/definition.json'),
  'shaderFullscreen': require('@/assets/embedded-games/shaderFullscreen/definition.json'),
  'shaderMulti': require('@/assets/embedded-games/shaderMulti/definition.json'),
  'shaderRainbow': require('@/assets/embedded-games/shaderRainbow/definition.json'),
  'slopeggle': require('@/assets/embedded-games/slopeggle/definition.json'),
  'snake': require('@/assets/embedded-games/snake/definition.json'),
  'sokoban': require('@/assets/embedded-games/sokoban/definition.json'),
  'tweenToggleCube': require('@/assets/embedded-games/tweenToggleCube/definition.json'),
};

export const EMBEDDED_METADATA: Record<string, unknown> = {
  'ballSort': require('@/assets/embedded-games/ballSort/metadata.json'),
  'breakoutBouncer': require('@/assets/embedded-games/breakoutBouncer/metadata.json'),
  'flappyBird': require('@/assets/embedded-games/flappyBird/metadata.json'),
  'gemCrush': require('@/assets/embedded-games/gemCrush/metadata.json'),
  'headsUp': require('@/assets/embedded-games/headsUp/metadata.json'),
  'kishimisuSwirl': require('@/assets/embedded-games/kishimisuSwirl/metadata.json'),
  'minefield': require('@/assets/embedded-games/minefield/metadata.json'),
  'mrPotatoHead': require('@/assets/embedded-games/mrPotatoHead/metadata.json'),
  'shaderCRT': require('@/assets/embedded-games/shaderCRT/metadata.json'),
  'shaderFullscreen': require('@/assets/embedded-games/shaderFullscreen/metadata.json'),
  'shaderMulti': require('@/assets/embedded-games/shaderMulti/metadata.json'),
  'shaderRainbow': require('@/assets/embedded-games/shaderRainbow/metadata.json'),
  'slopeggle': require('@/assets/embedded-games/slopeggle/metadata.json'),
  'snake': require('@/assets/embedded-games/snake/metadata.json'),
  'sokoban': require('@/assets/embedded-games/sokoban/metadata.json'),
  'tweenToggleCube': require('@/assets/embedded-games/tweenToggleCube/metadata.json'),
};
