// ---------------------------------------------------------------------------
// Effect Metadata — UI parameter definitions for test page
// ---------------------------------------------------------------------------

import type { EffectParamSchema, EffectType, UniformType } from "./types";

export type EffectCategory =
	| "glow"
	| "distortion"
	| "color"
	| "postProcess"
	| "artistic";

/**
 * @deprecated Use EffectParamSchema from types.ts instead
 */
export interface EffectParamMeta {
	key: string;
	type: "number" | "color" | "boolean" | "select";
	displayName: string;
	min?: number;
	max?: number;
	step?: number;
	options?: string[];
	defaultValue: number | string | boolean;
}

export interface EffectMetadata {
	type: EffectType;
	displayName: string;
	description: string;
	category: EffectCategory;
	params: EffectParamMeta[];
	defaultValues: Record<string, unknown>;
}

export const EFFECT_METADATA: Record<EffectType, EffectMetadata> = {
	glow: {
		type: "glow",
		displayName: "Outer Glow",
		description: "Soft luminous halo around the object",
		category: "glow",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#00ffff",
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 1,
				max: 50,
				step: 1,
				defaultValue: 15,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0.1,
				max: 2,
				step: 0.1,
				defaultValue: 0.8,
			},
			{
				key: "pulse",
				type: "boolean",
				displayName: "Pulse",
				defaultValue: false,
			},
			{
				key: "pulseSpeed",
				type: "number",
				displayName: "Pulse Speed",
				min: 0.5,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: {
			type: "glow",
			color: "#00ffff",
			radius: 15,
			intensity: 0.8,
		},
	},
	innerGlow: {
		type: "innerGlow",
		displayName: "Inner Glow",
		description: "Glow from inside the edges",
		category: "glow",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffff",
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 1,
				max: 30,
				step: 1,
				defaultValue: 10,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0.1,
				max: 1.5,
				step: 0.1,
				defaultValue: 0.6,
			},
			{
				key: "feather",
				type: "number",
				displayName: "Feather",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
		],
		defaultValues: {
			type: "innerGlow",
			color: "#ffffff",
			radius: 10,
			intensity: 0.6,
		},
	},
	outline: {
		type: "outline",
		displayName: "Outline",
		description: "Colored border around the object",
		category: "artistic",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#000000",
			},
			{
				key: "width",
				type: "number",
				displayName: "Width",
				min: 1,
				max: 10,
				step: 1,
				defaultValue: 2,
			},
			{
				key: "position",
				type: "select",
				displayName: "Position",
				options: ["outer", "inner", "center"],
				defaultValue: "outer",
			},
		],
		defaultValues: {
			type: "outline",
			color: "#000000",
			width: 2,
			position: "outer",
		},
	},
	dropShadow: {
		type: "dropShadow",
		displayName: "Drop Shadow",
		description: "Shadow cast below the object",
		category: "glow",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#000000",
			},
			{
				key: "offsetX",
				type: "number",
				displayName: "Offset X",
				min: -20,
				max: 20,
				step: 1,
				defaultValue: 4,
			},
			{
				key: "offsetY",
				type: "number",
				displayName: "Offset Y",
				min: -20,
				max: 20,
				step: 1,
				defaultValue: 4,
			},
			{
				key: "blur",
				type: "number",
				displayName: "Blur",
				min: 0,
				max: 30,
				step: 1,
				defaultValue: 8,
			},
		],
		defaultValues: {
			type: "dropShadow",
			color: "#000000",
			offsetX: 4,
			offsetY: 4,
			blur: 8,
		},
	},
	tint: {
		type: "tint",
		displayName: "Color Tint",
		description: "Shift colors toward a target",
		category: "color",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ff0000",
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "preserveLuminance",
				type: "boolean",
				displayName: "Preserve Luminance",
				defaultValue: true,
			},
		],
		defaultValues: { type: "tint", color: "#ff0000", intensity: 0.5 },
	},
	holographic: {
		type: "holographic",
		displayName: "Holographic",
		description: "Rainbow-shifting iridescent effect",
		category: "artistic",
		params: [
			{
				key: "speed",
				type: "number",
				displayName: "Speed",
				min: 0.1,
				max: 3,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "saturation",
				type: "number",
				displayName: "Saturation",
				min: 0.5,
				max: 1.5,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "scanlines",
				type: "boolean",
				displayName: "Scanlines",
				defaultValue: true,
			},
			{
				key: "scanlineSpacing",
				type: "number",
				displayName: "Scanline Spacing",
				min: 2,
				max: 10,
				step: 1,
				defaultValue: 4,
			},
		],
		defaultValues: {
			type: "holographic",
			speed: 0.5,
			saturation: 1,
			scanlines: true,
		},
	},
	pixelate: {
		type: "pixelate",
		displayName: "Pixelate",
		description: "Reduce to chunky pixels",
		category: "distortion",
		params: [
			{
				key: "pixelSize",
				type: "number",
				displayName: "Pixel Size",
				min: 2,
				max: 32,
				step: 1,
				defaultValue: 8,
			},
			{
				key: "animated",
				type: "boolean",
				displayName: "Animated",
				defaultValue: false,
			},
			{
				key: "animationSpeed",
				type: "number",
				displayName: "Animation Speed",
				min: 0.5,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "pixelate", pixelSize: 8 },
	},
	dissolve: {
		type: "dissolve",
		displayName: "Dissolve",
		description: "Break apart into noise",
		category: "distortion",
		params: [
			{
				key: "progress",
				type: "number",
				displayName: "Progress",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "noiseScale",
				type: "number",
				displayName: "Noise Scale",
				min: 5,
				max: 50,
				step: 1,
				defaultValue: 20,
			},
			{
				key: "edgeWidth",
				type: "number",
				displayName: "Edge Width",
				min: 0.01,
				max: 0.2,
				step: 0.01,
				defaultValue: 0.05,
			},
			{
				key: "edgeColor",
				type: "color",
				displayName: "Edge Color",
				defaultValue: "#ff8800",
			},
		],
		defaultValues: {
			type: "dissolve",
			progress: 0,
			noiseScale: 20,
			edgeWidth: 0.05,
			edgeColor: "#ff8800",
		},
	},
	waveDistortion: {
		type: "waveDistortion",
		displayName: "Wave Distortion",
		description: "Rippling wave warp effect",
		category: "distortion",
		params: [
			{
				key: "amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0.01,
				max: 0.1,
				step: 0.01,
				defaultValue: 0.03,
			},
			{
				key: "frequency",
				type: "number",
				displayName: "Frequency",
				min: 5,
				max: 50,
				step: 1,
				defaultValue: 15,
			},
			{
				key: "speed",
				type: "number",
				displayName: "Speed",
				min: 0.5,
				max: 5,
				step: 0.1,
				defaultValue: 2,
			},
			{
				key: "direction",
				type: "select",
				displayName: "Direction",
				options: ["horizontal", "vertical", "both"],
				defaultValue: "horizontal",
			},
		],
		defaultValues: {
			type: "waveDistortion",
			amplitude: 0.03,
			frequency: 15,
			speed: 2,
		},
	},
	shockwave: {
		type: "shockwave",
		displayName: "Shockwave",
		description: "Expanding ripple from a point",
		category: "distortion",
		params: [
			{
				key: "centerX",
				type: "number",
				displayName: "Center X",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "centerY",
				type: "number",
				displayName: "Center Y",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "thickness",
				type: "number",
				displayName: "Thickness",
				min: 0.05,
				max: 0.5,
				step: 0.01,
				defaultValue: 0.1,
			},
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0.01,
				max: 0.2,
				step: 0.01,
				defaultValue: 0.05,
			},
		],
		defaultValues: {
			type: "shockwave",
			centerX: 0.5,
			centerY: 0.5,
			radius: 0,
			thickness: 0.1,
			strength: 0.05,
		},
	},
	chromaticAberration: {
		type: "chromaticAberration",
		displayName: "Chromatic Aberration",
		description: "RGB color channel separation",
		category: "distortion",
		params: [
			{
				key: "offsetX",
				type: "number",
				displayName: "Offset X",
				min: 0,
				max: 20,
				step: 1,
				defaultValue: 5,
			},
			{
				key: "offsetY",
				type: "number",
				displayName: "Offset Y",
				min: 0,
				max: 20,
				step: 1,
				defaultValue: 0,
			},
			{
				key: "animated",
				type: "boolean",
				displayName: "Animated",
				defaultValue: false,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
		],
		defaultValues: {
			type: "chromaticAberration",
			offsetX: 5,
			offsetY: 0,
			intensity: 0.5,
		},
	},
	vignette: {
		type: "vignette",
		displayName: "Vignette",
		description: "Darken the edges",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 0.2,
				max: 1,
				step: 0.1,
				defaultValue: 0.7,
			},
			{
				key: "softness",
				type: "number",
				displayName: "Softness",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#000000",
			},
		],
		defaultValues: {
			type: "vignette",
			intensity: 0.5,
			radius: 0.7,
			softness: 0.5,
		},
	},
	scanlines: {
		type: "scanlines",
		displayName: "Scanlines",
		description: "CRT-style horizontal lines",
		category: "postProcess",
		params: [
			{
				key: "spacing",
				type: "number",
				displayName: "Spacing",
				min: 2,
				max: 10,
				step: 1,
				defaultValue: 4,
			},
			{
				key: "thickness",
				type: "number",
				displayName: "Thickness",
				min: 1,
				max: 3,
				step: 0.5,
				defaultValue: 1,
			},
			{
				key: "animated",
				type: "boolean",
				displayName: "Animated",
				defaultValue: true,
			},
			{
				key: "speed",
				type: "number",
				displayName: "Speed",
				min: 10,
				max: 100,
				step: 5,
				defaultValue: 50,
			},
		],
		defaultValues: {
			type: "scanlines",
			spacing: 4,
			thickness: 1,
			animated: true,
			speed: 50,
		},
	},
	posterize: {
		type: "posterize",
		displayName: "Posterize",
		description: "Reduce color levels",
		category: "color",
		params: [
			{
				key: "levels",
				type: "number",
				displayName: "Levels",
				min: 2,
				max: 16,
				step: 1,
				defaultValue: 4,
			},
			{
				key: "gamma",
				type: "number",
				displayName: "Gamma",
				min: 0.5,
				max: 2,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "posterize", levels: 4, gamma: 1 },
	},
	blur: {
		type: "blur",
		displayName: "Blur",
		description: "Gaussian blur effect",
		category: "postProcess",
		params: [
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 1,
				max: 30,
				step: 1,
				defaultValue: 5,
			},
		],
		defaultValues: { type: "blur", radius: 5 },
	},
	motionBlur: {
		type: "motionBlur",
		displayName: "Motion Blur",
		description: "Directional blur for speed",
		category: "postProcess",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "angle",
				type: "number",
				displayName: "Angle",
				min: 0,
				max: 360,
				step: 15,
				defaultValue: 0,
			},
			{
				key: "samples",
				type: "number",
				displayName: "Samples",
				min: 3,
				max: 15,
				step: 2,
				defaultValue: 7,
			},
		],
		defaultValues: { type: "motionBlur", strength: 0.5, angle: 0, samples: 7 },
	},
	rimLight: {
		type: "rimLight",
		displayName: "Rim Light",
		description: "Edge glow lighting effect",
		category: "glow",
		params: [
			{
				key: "color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ff00ff",
			},
			{
				key: "width",
				type: "number",
				displayName: "Width",
				min: 1,
				max: 10,
				step: 1,
				defaultValue: 3,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0.5,
				max: 2,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "falloff",
				type: "number",
				displayName: "Falloff",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
		],
		defaultValues: {
			type: "rimLight",
			color: "#ff00ff",
			width: 3,
			intensity: 1,
		},
	},
	bloom: {
		type: "bloom",
		displayName: "Bloom",
		description: "Bright areas glow",
		category: "postProcess",
		params: [
			{
				key: "threshold",
				type: "number",
				displayName: "Threshold",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.8,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1.5,
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 0,
				max: 10,
				step: 0.5,
				defaultValue: 3,
			},
		],
		defaultValues: { type: "bloom", threshold: 0.8, intensity: 1.5, radius: 3 },
	},
	nightVision: {
		type: "nightVision",
		displayName: "Night Vision",
		description: "Green tactical vision with noise",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.8,
			},
			{
				key: "noiseStrength",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.3,
			},
			{
				key: "scanlineStrength",
				type: "number",
				displayName: "Scanlines",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.1,
			},
			{
				key: "vignetteSize",
				type: "number",
				displayName: "Vignette",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.4,
			},
		],
		defaultValues: {
			type: "nightVision",
			intensity: 0.8,
			noiseStrength: 0.3,
			scanlineStrength: 0.1,
			vignetteSize: 0.4,
		},
	},
	speedLines: {
		type: "speedLines",
		displayName: "Speed Lines",
		description: "Anime-style radial motion lines",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.5,
			},
			{
				key: "density",
				type: "number",
				displayName: "Density",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.2,
			},
			{
				key: "speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 10,
				step: 0.5,
				defaultValue: 2.0,
			},
		],
		defaultValues: {
			type: "speedLines",
			intensity: 0.5,
			density: 0.2,
			speed: 2.0,
		},
	},
	underwater: {
		type: "underwater",
		displayName: "Underwater",
		description: "Wavy distortion with blue tint",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.8,
			},
			{
				key: "waveSpeed",
				type: "number",
				displayName: "Wave Speed",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1.0,
			},
			{
				key: "waveFrequency",
				type: "number",
				displayName: "Frequency",
				min: 1,
				max: 20,
				step: 1,
				defaultValue: 10.0,
			},
			{
				key: "waveAmplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 0.05,
				step: 0.001,
				defaultValue: 0.01,
			},
			{
				key: "waterTint",
				type: "color",
				displayName: "Tint",
				defaultValue: "#0066cc",
			},
		],
		defaultValues: {
			type: "underwater",
			intensity: 0.8,
			waveSpeed: 1.0,
			waveFrequency: 10.0,
			waveAmplitude: 0.01,
			waterTint: "#0066cc",
		},
	},
	halftone: {
		type: "halftone",
		displayName: "Halftone",
		description: "CMYK dot pattern print effect",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 1.0,
			},
			{
				key: "dotSize",
				type: "number",
				displayName: "Dot Size",
				min: 1,
				max: 50,
				step: 1,
				defaultValue: 8.0,
			},
			{
				key: "contrast",
				type: "number",
				displayName: "Contrast",
				min: 1,
				max: 5,
				step: 0.1,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "halftone",
			intensity: 1.0,
			dotSize: 8.0,
			contrast: 1.0,
		},
	},
	oldFilm: {
		type: "oldFilm",
		displayName: "Old Film",
		description: "Vintage movie look with scratches",
		category: "postProcess",
		params: [
			{
				key: "sepiaStrength",
				type: "number",
				displayName: "Sepia",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.8,
			},
			{
				key: "scratchStrength",
				type: "number",
				displayName: "Scratches",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.3,
			},
			{
				key: "noiseStrength",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.2,
			},
			{
				key: "vignetteSize",
				type: "number",
				displayName: "Vignette",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 0.4,
			},
		],
		defaultValues: {
			type: "oldFilm",
			sepiaStrength: 0.8,
			scratchStrength: 0.3,
			noiseStrength: 0.2,
			vignetteSize: 0.4,
		},
	},
	thermalVision: {
		type: "thermalVision",
		displayName: "Thermal Vision",
		description: "Heat-map style color gradient",
		category: "postProcess",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.1,
				defaultValue: 1.0,
			},
		],
		defaultValues: { type: "thermalVision", intensity: 1.0 },
	},
	ascii: {
		type: "ascii",
		displayName: "ASCII Art",
		description: "Convert screen to text characters",
		category: "postProcess",
		params: [
			{
				key: "pixelSize",
				type: "number",
				displayName: "Char Size",
				min: 4,
				max: 32,
				step: 2,
				defaultValue: 8.0,
			},
			{
				key: "monochrome",
				type: "boolean",
				displayName: "Monochrome",
				defaultValue: false,
			},
			{
				key: "color",
				type: "color",
				displayName: "Tint",
				defaultValue: "#00ff00",
			},
		],
		defaultValues: {
			type: "ascii",
			pixelSize: 8.0,
			monochrome: false,
			color: "#00ff00",
		},
	},
	ripple: {
		type: "ripple",
		displayName: "Ripple Field",
		description: "Distortion based on entity movement",
		category: "distortion",
		params: [
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 0.1,
				step: 0.001,
				defaultValue: 0.02,
			},
			{
				key: "speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1.0,
			},
		],
		defaultValues: { type: "ripple", intensity: 0.02, speed: 1.0 },
	},
	rbAurora: {
		type: "rbAurora",
		displayName: "RB Aurora",
		description: "React Bits aurora generator with noise-driven light curtains",
		category: "postProcess",
		params: [
			{
				key: "u_amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 3,
				step: 0.05,
				defaultValue: 1.0,
			},
			{
				key: "u_blend",
				type: "number",
				displayName: "Blend",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "u_color_stop_a",
				type: "color",
				displayName: "Color Stop A",
				defaultValue: "#5227ff",
			},
			{
				key: "u_color_stop_b",
				type: "color",
				displayName: "Color Stop B",
				defaultValue: "#7cff67",
			},
			{
				key: "u_color_stop_c",
				type: "color",
				displayName: "Color Stop C",
				defaultValue: "#5227ff",
			},
		],
		defaultValues: {
			type: "rbAurora",
			u_amplitude: 1.0,
			u_blend: 0.5,
			u_color_stop_a: "#5227ff",
			u_color_stop_b: "#7cff67",
			u_color_stop_c: "#5227ff",
		},
	},
	rbBalatro: {
		type: "rbBalatro",
		displayName: "RB Balatro",
		description: "React Bits Balatro-inspired psychedelic vortex generator",
		category: "postProcess",
		params: [
			{
				key: "u_spin_rotation",
				type: "number",
				displayName: "Spin Rotation",
				min: -10,
				max: 10,
				step: 0.1,
				defaultValue: -2.0,
			},
			{
				key: "u_spin_speed",
				type: "number",
				displayName: "Spin Speed",
				min: 0,
				max: 20,
				step: 0.1,
				defaultValue: 7.0,
			},
			{
				key: "u_contrast",
				type: "number",
				displayName: "Contrast",
				min: 0.5,
				max: 8,
				step: 0.1,
				defaultValue: 3.5,
			},
			{
				key: "u_lighting",
				type: "number",
				displayName: "Lighting",
				min: 0,
				max: 2,
				step: 0.05,
				defaultValue: 0.4,
			},
			{
				key: "u_spin_amount",
				type: "number",
				displayName: "Spin Amount",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.25,
			},
			{
				key: "u_color1",
				type: "color",
				displayName: "Color 1",
				defaultValue: "#de443b",
			},
			{
				key: "u_color2",
				type: "color",
				displayName: "Color 2",
				defaultValue: "#006bb4",
			},
			{
				key: "u_color3",
				type: "color",
				displayName: "Color 3",
				defaultValue: "#162325",
			},
		],
		defaultValues: {
			type: "rbBalatro",
			u_spin_rotation: -2.0,
			u_spin_speed: 7.0,
			u_contrast: 3.5,
			u_lighting: 0.4,
			u_spin_amount: 0.25,
			u_color1: "#de443b",
			u_color2: "#006bb4",
			u_color3: "#162325",
		},
	},
	rbColorBends: {
		type: "rbColorBends",
		displayName: "RB Color Bends",
		description:
			"React Bits warped color-bend generator with pointer-reactive parallax",
		category: "postProcess",
		params: [
			{
				key: "u_speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 5,
				step: 0.01,
				defaultValue: 0.2,
			},
			{
				key: "u_scale",
				type: "number",
				displayName: "Scale",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_frequency",
				type: "number",
				displayName: "Frequency",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_warp_strength",
				type: "number",
				displayName: "Warp Strength",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_mouse_influence",
				type: "number",
				displayName: "Mouse Influence",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_parallax",
				type: "number",
				displayName: "Parallax",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "u_noise",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.1,
			},
		],
		defaultValues: {
			type: "rbColorBends",
			u_speed: 0.2,
			u_scale: 1.0,
			u_frequency: 1.0,
			u_warp_strength: 1.0,
			u_mouse_influence: 1.0,
			u_parallax: 0.5,
			u_noise: 0.1,
		},
	},
	rbDarkVeil: {
		type: "rbDarkVeil",
		displayName: "RB Dark Veil",
		description:
			"React Bits dark veil generator with hue, scanline, and warp controls",
		category: "postProcess",
		params: [
			{
				key: "u_hue_shift",
				type: "number",
				displayName: "Hue Shift",
				min: -180,
				max: 180,
				step: 1,
				defaultValue: 0,
			},
			{
				key: "u_noise",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 0.3,
				step: 0.005,
				defaultValue: 0,
			},
			{
				key: "u_scan",
				type: "number",
				displayName: "Scan",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "u_scan_freq",
				type: "number",
				displayName: "Scan Freq",
				min: 0,
				max: 0.5,
				step: 0.005,
				defaultValue: 0,
			},
			{
				key: "u_warp",
				type: "number",
				displayName: "Warp",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
		],
		defaultValues: {
			type: "rbDarkVeil",
			u_hue_shift: 0,
			u_noise: 0,
			u_scan: 0,
			u_scan_freq: 0,
			u_warp: 0,
		},
	},
	rbFaultyTerminal: {
		type: "rbFaultyTerminal",
		displayName: "RB Faulty Terminal",
		description:
			"React Bits terminal-style generator with glitch, CRT curve, and scanline controls",
		category: "postProcess",
		params: [
			{
				key: "u_scale",
				type: "number",
				displayName: "Scale",
				min: 0.5,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_digit_size",
				type: "number",
				displayName: "Digit Size",
				min: 0.5,
				max: 3,
				step: 0.01,
				defaultValue: 1.5,
			},
			{
				key: "u_scanline_intensity",
				type: "number",
				displayName: "Scanline Intensity",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_glitch_amount",
				type: "number",
				displayName: "Glitch Amount",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_chromatic_aberration",
				type: "number",
				displayName: "Chromatic Aberration",
				min: 0,
				max: 8,
				step: 0.1,
				defaultValue: 0,
			},
			{
				key: "u_curvature",
				type: "number",
				displayName: "Curvature",
				min: 0,
				max: 0.4,
				step: 0.01,
				defaultValue: 0.2,
			},
			{
				key: "u_brightness",
				type: "number",
				displayName: "Brightness",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbFaultyTerminal",
			u_scale: 1.0,
			u_digit_size: 1.5,
			u_scanline_intensity: 0.3,
			u_glitch_amount: 1.0,
			u_chromatic_aberration: 0,
			u_curvature: 0.2,
			u_brightness: 1.0,
		},
	},
	rbFloatingLines: {
		type: "rbFloatingLines",
		displayName: "RB Floating Lines",
		description:
			"React Bits floating line waves with bend and parallax controls",
		category: "postProcess",
		params: [
			{
				key: "u_animation_speed",
				type: "number",
				displayName: "Animation Speed",
				min: 0,
				max: 5,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_bend_radius",
				type: "number",
				displayName: "Bend Radius",
				min: 0.5,
				max: 20,
				step: 0.1,
				defaultValue: 5.0,
			},
			{
				key: "u_bend_strength",
				type: "number",
				displayName: "Bend Strength",
				min: -2,
				max: 2,
				step: 0.01,
				defaultValue: -0.5,
			},
			{
				key: "u_parallax_strength",
				type: "number",
				displayName: "Parallax Strength",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.2,
			},
		],
		defaultValues: {
			type: "rbFloatingLines",
			u_animation_speed: 1.0,
			u_bend_radius: 5.0,
			u_bend_strength: -0.5,
			u_parallax_strength: 0.2,
		},
	},
	rbLightRays: {
		type: "rbLightRays",
		displayName: "RB Light Rays",
		description:
			"React Bits light rays generator with spread, length, and distortion controls",
		category: "postProcess",
		params: [
			{
				key: "u_rays_color",
				type: "color",
				displayName: "Rays Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_rays_speed",
				type: "number",
				displayName: "Rays Speed",
				min: 0,
				max: 5,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_light_spread",
				type: "number",
				displayName: "Light Spread",
				min: 0.05,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_ray_length",
				type: "number",
				displayName: "Ray Length",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 2.0,
			},
			{
				key: "u_fade_distance",
				type: "number",
				displayName: "Fade Distance",
				min: 0.1,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_noise_amount",
				type: "number",
				displayName: "Noise Amount",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "u_distortion",
				type: "number",
				displayName: "Distortion",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 0,
			},
		],
		defaultValues: {
			type: "rbLightRays",
			u_rays_color: "#ffffff",
			u_rays_speed: 1.0,
			u_light_spread: 1.0,
			u_ray_length: 2.0,
			u_fade_distance: 1.0,
			u_noise_amount: 0,
			u_distortion: 0,
		},
	},
	rbPlasma: {
		type: "rbPlasma",
		displayName: "RB Plasma",
		description:
			"React Bits plasma field generator with direction, scale, and opacity controls",
		category: "postProcess",
		params: [
			{
				key: "u_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 5,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_direction",
				type: "number",
				displayName: "Direction",
				min: -1,
				max: 1,
				step: 2,
				defaultValue: 1.0,
			},
			{
				key: "u_scale",
				type: "number",
				displayName: "Scale",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_opacity",
				type: "number",
				displayName: "Opacity",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbPlasma",
			u_color: "#ffffff",
			u_speed: 1.0,
			u_direction: 1.0,
			u_scale: 1.0,
			u_opacity: 1.0,
		},
	},
	rbPrism: {
		type: "rbPrism",
		displayName: "RB Prism",
		description:
			"React Bits prism generator with volumetric pyramid glow and spectral controls",
		category: "postProcess",
		params: [
			{
				key: "u_height",
				type: "number",
				displayName: "Height",
				min: 0.5,
				max: 8,
				step: 0.01,
				defaultValue: 3.5,
			},
			{
				key: "u_base_width",
				type: "number",
				displayName: "Base Width",
				min: 0.5,
				max: 10,
				step: 0.01,
				defaultValue: 5.5,
			},
			{
				key: "u_glow",
				type: "number",
				displayName: "Glow",
				min: 0,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_noise",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "u_hue_shift",
				type: "number",
				displayName: "Hue Shift",
				min: -3.1416,
				max: 3.1416,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "u_color_frequency",
				type: "number",
				displayName: "Color Frequency",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_bloom",
				type: "number",
				displayName: "Bloom",
				min: 0,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbPrism",
			u_height: 3.5,
			u_base_width: 5.5,
			u_glow: 1.0,
			u_noise: 0.5,
			u_hue_shift: 0,
			u_color_frequency: 1.0,
			u_bloom: 1.0,
		},
	},
	rbSilk: {
		type: "rbSilk",
		displayName: "RB Silk",
		description:
			"React Bits silk fabric generator with rotational flow and grain control",
		category: "postProcess",
		params: [
			{
				key: "u_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#7b7481",
			},
			{
				key: "u_speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 10,
				step: 0.1,
				defaultValue: 5.0,
			},
			{
				key: "u_scale",
				type: "number",
				displayName: "Scale",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_rotation",
				type: "number",
				displayName: "Rotation",
				min: -6.2832,
				max: 6.2832,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "u_noise_intensity",
				type: "number",
				displayName: "Noise Intensity",
				min: 0,
				max: 3,
				step: 0.01,
				defaultValue: 1.5,
			},
		],
		defaultValues: {
			type: "rbSilk",
			u_color: "#7b7481",
			u_speed: 5.0,
			u_scale: 1.0,
			u_rotation: 0,
			u_noise_intensity: 1.5,
		},
	},
	rbGalaxy: {
		type: "rbGalaxy",
		displayName: "RB Galaxy",
		description:
			"React Bits galaxy starfield with hue shift and twinkle controls",
		category: "postProcess",
		params: [
			{
				key: "u_density",
				type: "number",
				displayName: "Density",
				min: 0.1,
				max: 4,
				step: 0.05,
				defaultValue: 1.0,
			},
			{
				key: "u_hue_shift",
				type: "number",
				displayName: "Hue Shift",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 140.0,
			},
			{
				key: "u_glow_intensity",
				type: "number",
				displayName: "Glow Intensity",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_twinkle_intensity",
				type: "number",
				displayName: "Twinkle Intensity",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_rotation_speed",
				type: "number",
				displayName: "Rotation Speed",
				min: -2,
				max: 2,
				step: 0.01,
				defaultValue: 0.1,
			},
		],
		defaultValues: {
			type: "rbGalaxy",
			u_density: 1.0,
			u_hue_shift: 140.0,
			u_glow_intensity: 0.3,
			u_twinkle_intensity: 0.3,
			u_rotation_speed: 0.1,
		},
	},
	rbGradientBlinds: {
		type: "rbGradientBlinds",
		displayName: "RB Gradient Blinds",
		description:
			"React Bits striped gradient blinds with spotlight and distortion",
		category: "postProcess",
		params: [
			{
				key: "u_angle",
				type: "number",
				displayName: "Angle",
				min: -180,
				max: 180,
				step: 1,
				defaultValue: 0.0,
			},
			{
				key: "u_noise",
				type: "number",
				displayName: "Noise",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_blind_count",
				type: "number",
				displayName: "Blind Count",
				min: 1,
				max: 64,
				step: 1,
				defaultValue: 16.0,
			},
			{
				key: "u_distort",
				type: "number",
				displayName: "Distort",
				min: 0,
				max: 4,
				step: 0.01,
				defaultValue: 0.0,
			},
			{
				key: "u_spotlight_opacity",
				type: "number",
				displayName: "Spotlight Opacity",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbGradientBlinds",
			u_angle: 0.0,
			u_noise: 0.3,
			u_blind_count: 16.0,
			u_distort: 0.0,
			u_spotlight_opacity: 1.0,
		},
	},
	rbGrainient: {
		type: "rbGrainient",
		displayName: "RB Grainient",
		description:
			"React Bits warped gradient with animated grain and color controls",
		category: "postProcess",
		params: [
			{
				key: "u_time_speed",
				type: "number",
				displayName: "Time Speed",
				min: 0,
				max: 3,
				step: 0.01,
				defaultValue: 0.25,
			},
			{
				key: "u_warp_strength",
				type: "number",
				displayName: "Warp Strength",
				min: 0,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_warp_frequency",
				type: "number",
				displayName: "Warp Frequency",
				min: 0.1,
				max: 20,
				step: 0.1,
				defaultValue: 5.0,
			},
			{
				key: "u_grain_amount",
				type: "number",
				displayName: "Grain Amount",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.1,
			},
			{
				key: "u_contrast",
				type: "number",
				displayName: "Contrast",
				min: 0.1,
				max: 4,
				step: 0.01,
				defaultValue: 1.5,
			},
			{
				key: "u_saturation",
				type: "number",
				displayName: "Saturation",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_color1",
				type: "color",
				displayName: "Color 1",
				defaultValue: "#ff9ffc",
			},
			{
				key: "u_color2",
				type: "color",
				displayName: "Color 2",
				defaultValue: "#5227ff",
			},
			{
				key: "u_color3",
				type: "color",
				displayName: "Color 3",
				defaultValue: "#b19eef",
			},
		],
		defaultValues: {
			type: "rbGrainient",
			u_time_speed: 0.25,
			u_warp_strength: 1.0,
			u_warp_frequency: 5.0,
			u_grain_amount: 0.1,
			u_contrast: 1.5,
			u_saturation: 1.0,
			u_color1: "#ff9ffc",
			u_color2: "#5227ff",
			u_color3: "#b19eef",
		},
	},
	rbIridescence: {
		type: "rbIridescence",
		displayName: "RB Iridescence",
		description: "React Bits iridescent interference field generator",
		category: "postProcess",
		params: [
			{
				key: "u_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.1,
			},
			{
				key: "u_speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 5,
				step: 0.05,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbIridescence",
			u_color: "#ffffff",
			u_amplitude: 0.1,
			u_speed: 1.0,
		},
	},
	rbLightning: {
		type: "rbLightning",
		displayName: "RB Lightning",
		description: "React Bits lightning beam generator with fractal noise",
		category: "postProcess",
		params: [
			{
				key: "u_hue",
				type: "number",
				displayName: "Hue",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 230.0,
			},
			{
				key: "u_x_offset",
				type: "number",
				displayName: "X Offset",
				min: -2,
				max: 2,
				step: 0.01,
				defaultValue: 0.0,
			},
			{
				key: "u_speed",
				type: "number",
				displayName: "Speed",
				min: 0,
				max: 5,
				step: 0.05,
				defaultValue: 1.0,
			},
			{
				key: "u_intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 5,
				step: 0.05,
				defaultValue: 1.0,
			},
			{
				key: "u_size",
				type: "number",
				displayName: "Size",
				min: 0.1,
				max: 5,
				step: 0.05,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbLightning",
			u_hue: 230.0,
			u_x_offset: 0.0,
			u_speed: 1.0,
			u_intensity: 1.0,
			u_size: 1.0,
		},
	},
	rbLiquidChrome: {
		type: "rbLiquidChrome",
		displayName: "RB Liquid Chrome",
		description: "React Bits liquid chrome generator with recursive warping",
		category: "postProcess",
		params: [
			{
				key: "u_base_color",
				type: "color",
				displayName: "Base Color",
				defaultValue: "#1a1a1a",
			},
			{
				key: "u_amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_frequency_x",
				type: "number",
				displayName: "Frequency X",
				min: 0.1,
				max: 10,
				step: 0.1,
				defaultValue: 3.0,
			},
			{
				key: "u_frequency_y",
				type: "number",
				displayName: "Frequency Y",
				min: 0.1,
				max: 10,
				step: 0.1,
				defaultValue: 3.0,
			},
		],
		defaultValues: {
			type: "rbLiquidChrome",
			u_base_color: "#1a1a1a",
			u_amplitude: 0.3,
			u_frequency_x: 3.0,
			u_frequency_y: 3.0,
		},
	},
	rbMetaBalls: {
		type: "rbMetaBalls",
		displayName: "RB MetaBalls",
		description: "React Bits metaballs field with cursor blending",
		category: "postProcess",
		params: [
			{
				key: "u_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_cursor_color",
				type: "color",
				displayName: "Cursor Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_cursor_ball_size",
				type: "number",
				displayName: "Cursor Ball Size",
				min: 0.1,
				max: 8,
				step: 0.01,
				defaultValue: 3.0,
			},
			{
				key: "u_clump_factor",
				type: "number",
				displayName: "Clump Factor",
				min: 0.1,
				max: 3,
				step: 0.01,
				defaultValue: 1.0,
			},
		],
		defaultValues: {
			type: "rbMetaBalls",
			u_color: "#ffffff",
			u_cursor_color: "#ffffff",
			u_cursor_ball_size: 3.0,
			u_clump_factor: 1.0,
		},
	},
	rbOrb: {
		type: "rbOrb",
		displayName: "RB Orb",
		description: "React Bits orb with hue controls and hover-reactive warping",
		category: "postProcess",
		params: [
			{
				key: "u_hue_shift",
				type: "number",
				displayName: "Hue Shift",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 0.0,
			},
			{
				key: "u_hover_intensity",
				type: "number",
				displayName: "Hover Intensity",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.2,
			},
			{
				key: "u_rotation",
				type: "number",
				displayName: "Rotation",
				min: -6.2832,
				max: 6.2832,
				step: 0.01,
				defaultValue: 0.0,
			},
			{
				key: "u_background_color",
				type: "color",
				displayName: "Background Color",
				defaultValue: "#000000",
			},
		],
		defaultValues: {
			type: "rbOrb",
			u_hue_shift: 0.0,
			u_hover_intensity: 0.2,
			u_rotation: 0.0,
			u_background_color: "#000000",
		},
	},
	rbShapeBlur: {
		type: "rbShapeBlur",
		displayName: "RB Shape Blur",
		description: "React Bits SDF shape blur mask with pointer-softened edge",
		category: "postProcess",
		params: [
			{
				key: "u_shape_size",
				type: "number",
				displayName: "Shape Size",
				min: 0.1,
				max: 3,
				step: 0.01,
				defaultValue: 1.2,
			},
			{
				key: "u_roundness",
				type: "number",
				displayName: "Roundness",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.4,
			},
			{
				key: "u_border_size",
				type: "number",
				displayName: "Border Size",
				min: 0,
				max: 0.2,
				step: 0.001,
				defaultValue: 0.05,
			},
			{
				key: "u_circle_size",
				type: "number",
				displayName: "Circle Size",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.3,
			},
			{
				key: "u_circle_edge",
				type: "number",
				displayName: "Circle Edge",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
		],
		defaultValues: {
			type: "rbShapeBlur",
			u_shape_size: 1.2,
			u_roundness: 0.4,
			u_border_size: 0.05,
			u_circle_size: 0.3,
			u_circle_edge: 0.5,
		},
	},
	rbThreads: {
		type: "rbThreads",
		displayName: "RB Threads",
		description: "React Bits thread-line field with Perlin-driven filaments",
		category: "postProcess",
		params: [
			{
				key: "u_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffff",
			},
			{
				key: "u_amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 2,
				step: 0.01,
				defaultValue: 1.0,
			},
			{
				key: "u_distance",
				type: "number",
				displayName: "Distance",
				min: -1,
				max: 1,
				step: 0.01,
				defaultValue: 0.0,
			},
		],
		defaultValues: {
			type: "rbThreads",
			u_color: "#ffffff",
			u_amplitude: 1.0,
			u_distance: 0.0,
		},
	},
	fogOfWar: {
		type: "fogOfWar",
		displayName: "Fog of War",
		description: "Hide unexplored areas",
		category: "postProcess",
		params: [
			{
				key: "fogColor",
				type: "color",
				displayName: "Fog Color",
				defaultValue: "#00000080",
			},
			{
				key: "unexploredColor",
				type: "color",
				displayName: "Hidden Color",
				defaultValue: "#000000ff",
			},
			{
				key: "smoothness",
				type: "number",
				displayName: "Edge Smoothness",
				min: 0,
				max: 0.2,
				step: 0.01,
				defaultValue: 0.05,
			},
		],
		defaultValues: {
			type: "fogOfWar",
			fogColor: "#00000080",
			unexploredColor: "#000000ff",
			smoothness: 0.05,
		},
	},
	colorMatrix: {
		type: "colorMatrix",
		displayName: "Color Matrix",
		description: "Custom 4x5 color transformation",
		category: "color",
		params: [],
		defaultValues: {
			type: "colorMatrix",
			matrix: [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
		},
	},
	level: {
		type: "level",
		displayName: "Level",
		description: "Adjust brightness, contrast, gamma, and black/white point",
		category: "color",
		params: [
			{
				key: "brightness",
				type: "number",
				displayName: "Brightness",
				min: -1,
				max: 1,
				step: 0.05,
				defaultValue: 0,
			},
			{
				key: "contrast",
				type: "number",
				displayName: "Contrast",
				min: 0,
				max: 3,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "gamma",
				type: "number",
				displayName: "Gamma",
				min: 0.1,
				max: 3,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "black_point",
				type: "number",
				displayName: "Black Point",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "white_point",
				type: "number",
				displayName: "White Point",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 1,
			},
			{
				key: "opacity",
				type: "number",
				displayName: "Opacity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: {
			type: "level",
			brightness: 0,
			contrast: 1,
			gamma: 1,
			black_point: 0,
			white_point: 1,
			opacity: 1,
		},
	},
	ramp: {
		type: "ramp",
		displayName: "Ramp",
		description: "Generate procedural gradients (linear, radial, circular)",
		category: "artistic",
		params: [
			{
				key: "color_a",
				type: "color",
				displayName: "Color A",
				defaultValue: "#ffffffff",
			},
			{
				key: "color_b",
				type: "color",
				displayName: "Color B",
				defaultValue: "#000000ff",
			},
			{
				key: "ramp_type",
				type: "select",
				displayName: "Type",
				options: ["horizontal", "vertical", "radial", "circular"],
				defaultValue: "horizontal",
			},
			{
				key: "offset",
				type: "number",
				displayName: "Offset",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0,
			},
			{
				key: "smoothness",
				type: "number",
				displayName: "Smoothness",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: {
			type: "ramp",
			ramp_type: "horizontal",
			offset: 0,
			smoothness: 1,
		},
	},
	lfo: {
		type: "lfo",
		displayName: "LFO",
		description: "Low frequency oscillator for animated grayscale patterns",
		category: "artistic",
		params: [
			{
				key: "frequency",
				type: "number",
				displayName: "Frequency",
				min: 0.1,
				max: 20,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "amplitude",
				type: "number",
				displayName: "Amplitude",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "phase",
				type: "number",
				displayName: "Phase",
				min: 0,
				max: 6.28,
				step: 0.1,
				defaultValue: 0,
			},
			{
				key: "waveform",
				type: "select",
				displayName: "Waveform",
				options: ["sine", "square", "triangle", "sawtooth"],
				defaultValue: "sine",
			},
		],
		defaultValues: {
			type: "lfo",
			frequency: 1,
			amplitude: 1,
			phase: 0,
			waveform: "sine",
		},
	},
	constantColor: {
		type: "constantColor",
		displayName: "Constant Color",
		description: "Solid color fill",
		category: "artistic",
		params: [
			{
				key: "fill_color",
				type: "color",
				displayName: "Color",
				defaultValue: "#ffffffff",
			},
			{
				key: "opacity",
				type: "number",
				displayName: "Opacity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "constantColor" },
	},
	circle: {
		type: "circle",
		displayName: "Circle",
		description: "Procedural circle or ring shape",
		category: "artistic",
		params: [
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.4,
			},
			{
				key: "softness",
				type: "number",
				displayName: "Softness",
				min: 0,
				max: 0.5,
				step: 0.01,
				defaultValue: 0.02,
			},
			{
				key: "fill_color",
				type: "color",
				displayName: "Fill Color",
				defaultValue: "#ffffffff",
			},
			{
				key: "ring_width",
				type: "number",
				displayName: "Ring Width",
				min: 0,
				max: 0.5,
				step: 0.01,
				defaultValue: 0,
			},
		],
		defaultValues: {
			type: "circle",
			radius: 0.4,
			softness: 0.02,
			ring_width: 0,
		},
	},
	rectangle: {
		type: "rectangle",
		displayName: "Rectangle",
		description: "Procedural rectangle with optional rounded corners",
		category: "artistic",
		params: [
			{
				key: "corner_radius",
				type: "number",
				displayName: "Corner Radius",
				min: 0,
				max: 0.5,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "softness",
				type: "number",
				displayName: "Softness",
				min: 0,
				max: 0.5,
				step: 0.01,
				defaultValue: 0.02,
			},
			{
				key: "fill_color",
				type: "color",
				displayName: "Fill Color",
				defaultValue: "#ffffffff",
			},
		],
		defaultValues: { type: "rectangle", corner_radius: 0, softness: 0.02 },
	},
	transform: {
		type: "transform",
		displayName: "Transform",
		description: "Translate, scale, rotate, and tile the image",
		category: "distortion",
		params: [
			{
				key: "translate_x",
				type: "number",
				displayName: "Translate X",
				min: -1,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "translate_y",
				type: "number",
				displayName: "Translate Y",
				min: -1,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "scale_x",
				type: "number",
				displayName: "Scale X",
				min: 0.1,
				max: 10,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "scale_y",
				type: "number",
				displayName: "Scale Y",
				min: 0.1,
				max: 10,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "rotation",
				type: "number",
				displayName: "Rotation",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 0,
			},
		],
		defaultValues: {
			type: "transform",
			translate_x: 0,
			translate_y: 0,
			scale_x: 1,
			scale_y: 1,
			rotation: 0,
		},
	},
	displace: {
		type: "displace",
		displayName: "Displace",
		description: "Warp the image using noise-driven UV displacement",
		category: "distortion",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 100,
				step: 1,
				defaultValue: 10,
			},
			{
				key: "noise_scale",
				type: "number",
				displayName: "Noise Scale",
				min: 1,
				max: 50,
				step: 0.5,
				defaultValue: 10,
			},
			{
				key: "noise_speed",
				type: "number",
				displayName: "Noise Speed",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: {
			type: "displace",
			strength: 10,
			noise_scale: 10,
			noise_speed: 1,
		},
	},
	lookup: {
		type: "lookup",
		displayName: "Lookup",
		description: "Remap pixel luminance through a 3-point color gradient",
		category: "color",
		params: [
			{
				key: "color_low",
				type: "color",
				displayName: "Low Color",
				defaultValue: "#000000ff",
			},
			{
				key: "color_mid",
				type: "color",
				displayName: "Mid Color",
				defaultValue: "#808080ff",
			},
			{
				key: "color_high",
				type: "color",
				displayName: "High Color",
				defaultValue: "#ffffffff",
			},
			{
				key: "midpoint",
				type: "number",
				displayName: "Midpoint",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.5,
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "lookup", midpoint: 0.5, intensity: 1 },
	},
	math: {
		type: "math",
		displayName: "Math",
		description:
			"Per-pixel math operations (add, multiply, power, invert, step, etc.)",
		category: "color",
		params: [
			{
				key: "operation",
				type: "select",
				displayName: "Operation",
				options: [
					"add",
					"multiply",
					"power",
					"abs",
					"invert",
					"step",
					"smoothstep",
					"sin",
					"clamp",
				],
				defaultValue: "add",
			},
			{
				key: "value",
				type: "number",
				displayName: "Value",
				min: -2,
				max: 2,
				step: 0.05,
				defaultValue: 0,
			},
			{
				key: "range_min",
				type: "number",
				displayName: "Range Min",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0,
			},
			{
				key: "range_max",
				type: "number",
				displayName: "Range Max",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: {
			type: "math",
			operation: "add",
			value: 0,
			range_min: 0,
			range_max: 1,
		},
	},
	threshold: {
		type: "threshold",
		displayName: "Threshold",
		description: "Binary or soft luminance cutoff for masking",
		category: "color",
		params: [
			{
				key: "cutoff",
				type: "number",
				displayName: "Cutoff",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0.5,
			},
			{
				key: "softness",
				type: "number",
				displayName: "Softness",
				min: 0,
				max: 0.5,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "use_luminance",
				type: "boolean",
				displayName: "Use Luminance",
				defaultValue: true,
			},
			{
				key: "output_color",
				type: "color",
				displayName: "Output Color",
				defaultValue: "#ffffffff",
			},
			{
				key: "bg_color",
				type: "color",
				displayName: "Background Color",
				defaultValue: "#000000ff",
			},
		],
		defaultValues: {
			type: "threshold",
			cutoff: 0.5,
			softness: 0,
			use_luminance: true,
		},
	},
	hsvAdjust: {
		type: "hsvAdjust",
		displayName: "HSV Adjust",
		description: "Shift hue, adjust saturation and value independently",
		category: "color",
		params: [
			{
				key: "hue_shift",
				type: "number",
				displayName: "Hue Shift",
				min: -180,
				max: 180,
				step: 1,
				defaultValue: 0,
			},
			{
				key: "saturation",
				type: "number",
				displayName: "Saturation",
				min: 0,
				max: 3,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "value",
				type: "number",
				displayName: "Value",
				min: 0,
				max: 3,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "hsvAdjust", hue_shift: 0, saturation: 1, value: 1 },
	},
	edge: {
		type: "edge",
		displayName: "Edge Detect",
		description: "Sobel edge detection for sketch/neon effects",
		category: "artistic",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "threshold",
				type: "number",
				displayName: "Threshold",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.1,
			},
			{
				key: "edge_color",
				type: "color",
				displayName: "Edge Color",
				defaultValue: "#ffffffff",
			},
			{
				key: "bg_color",
				type: "color",
				displayName: "Background Color",
				defaultValue: "#000000ff",
			},
		],
		defaultValues: { type: "edge", strength: 1, threshold: 0.1 },
	},
	channelMix: {
		type: "channelMix",
		displayName: "Channel Mix",
		description: "Remap and swap RGBA channels",
		category: "color",
		params: [
			{
				key: "red_source",
				type: "select",
				displayName: "Red Source",
				options: ["R", "G", "B", "A", "luminance", "zero", "one"],
				defaultValue: "R",
			},
			{
				key: "green_source",
				type: "select",
				displayName: "Green Source",
				options: ["R", "G", "B", "A", "luminance", "zero", "one"],
				defaultValue: "G",
			},
			{
				key: "blue_source",
				type: "select",
				displayName: "Blue Source",
				options: ["R", "G", "B", "A", "luminance", "zero", "one"],
				defaultValue: "B",
			},
		],
		defaultValues: {
			type: "channelMix",
			red_source: "R",
			green_source: "G",
			blue_source: "B",
		},
	},
	crossFade: {
		type: "crossFade",
		displayName: "Cross Fade",
		description: "Crossfade between the image and a solid color",
		category: "postProcess",
		params: [
			{
				key: "mix_amount",
				type: "number",
				displayName: "Mix Amount",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.5,
			},
			{
				key: "fade_color",
				type: "color",
				displayName: "Fade Color",
				defaultValue: "#000000ff",
			},
			{
				key: "fade_mode",
				type: "select",
				displayName: "Fade Mode",
				options: ["linear", "smooth", "ease in", "ease out"],
				defaultValue: "linear",
			},
		],
		defaultValues: { type: "crossFade", mix_amount: 0.5, fade_mode: "linear" },
	},
	over: {
		type: "over",
		displayName: "Over",
		description: "Alpha-composite a color overlay with blend modes",
		category: "postProcess",
		params: [
			{
				key: "overlay_color",
				type: "color",
				displayName: "Overlay Color",
				defaultValue: "#ffffff80",
			},
			{
				key: "blend_mode",
				type: "select",
				displayName: "Blend Mode",
				options: ["normal", "multiply", "screen", "overlay", "soft light"],
				defaultValue: "normal",
			},
			{
				key: "opacity",
				type: "number",
				displayName: "Opacity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "over", blend_mode: "normal", opacity: 1 },
	},
	mirror: {
		type: "mirror",
		displayName: "Mirror",
		description: "Flip or mirror the image on X/Y axes",
		category: "distortion",
		params: [
			{
				key: "mirror_x",
				type: "boolean",
				displayName: "Mirror X",
				defaultValue: true,
			},
			{
				key: "mirror_y",
				type: "boolean",
				displayName: "Mirror Y",
				defaultValue: false,
			},
			{
				key: "mirror_mode",
				type: "select",
				displayName: "Mode",
				options: ["flip", "symmetry"],
				defaultValue: "flip",
			},
		],
		defaultValues: {
			type: "mirror",
			mirror_x: true,
			mirror_y: false,
			mirror_mode: "flip",
		},
	},
	crop: {
		type: "crop",
		displayName: "Crop",
		description: "Crop to a sub-region of the image",
		category: "postProcess",
		params: [
			{
				key: "left",
				type: "number",
				displayName: "Left",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "right",
				type: "number",
				displayName: "Right",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 1,
			},
			{
				key: "top",
				type: "number",
				displayName: "Top",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 0,
			},
			{
				key: "bottom",
				type: "number",
				displayName: "Bottom",
				min: 0,
				max: 1,
				step: 0.01,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "crop", left: 0, right: 1, top: 0, bottom: 1 },
	},
	resize: {
		type: "resize",
		displayName: "Resize",
		description: "Scale the image with bilinear or nearest filtering",
		category: "postProcess",
		params: [
			{
				key: "scale",
				type: "number",
				displayName: "Scale",
				min: 0.1,
				max: 4,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "filter_mode",
				type: "select",
				displayName: "Filter Mode",
				options: ["bilinear", "nearest"],
				defaultValue: "bilinear",
			},
		],
		defaultValues: { type: "resize", scale: 1, filter_mode: "bilinear" },
	},
	invert: {
		type: "invert",
		displayName: "Invert",
		description: "Invert/negate color channels",
		category: "color",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "invert_r",
				type: "boolean",
				displayName: "Invert Red",
				defaultValue: true,
			},
			{
				key: "invert_g",
				type: "boolean",
				displayName: "Invert Green",
				defaultValue: true,
			},
			{
				key: "invert_b",
				type: "boolean",
				displayName: "Invert Blue",
				defaultValue: true,
			},
		],
		defaultValues: {
			type: "invert",
			strength: 1,
			invert_r: true,
			invert_g: true,
			invert_b: true,
		},
	},
	emboss: {
		type: "emboss",
		displayName: "Emboss",
		description: "Relief/emboss effect with directional lighting",
		category: "artistic",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "angle",
				type: "number",
				displayName: "Angle",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 135,
			},
			{
				key: "blend_with_original",
				type: "number",
				displayName: "Blend Original",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.5,
			},
		],
		defaultValues: {
			type: "emboss",
			strength: 1,
			angle: 135,
			blend_with_original: 0.5,
		},
	},
	sharpen: {
		type: "sharpen",
		displayName: "Sharpen",
		description: "Unsharp mask sharpening to enhance detail",
		category: "postProcess",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: 0,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "radius",
				type: "number",
				displayName: "Radius",
				min: 0.5,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "sharpen", strength: 1, radius: 1 },
	},
	convolve: {
		type: "convolve",
		displayName: "Convolve",
		description: "Custom 3x3 convolution kernel",
		category: "postProcess",
		params: [
			{
				key: "kernel_center",
				type: "number",
				displayName: "Center",
				min: -5,
				max: 5,
				step: 0.1,
				defaultValue: 1,
			},
			{
				key: "normalize",
				type: "boolean",
				displayName: "Normalize",
				defaultValue: true,
			},
			{
				key: "bias",
				type: "number",
				displayName: "Bias",
				min: -1,
				max: 1,
				step: 0.05,
				defaultValue: 0,
			},
		],
		defaultValues: {
			type: "convolve",
			kernel_center: 1,
			normalize: true,
			bias: 0,
		},
	},
	kaleidoscope: {
		type: "kaleidoscope",
		displayName: "Kaleidoscope",
		description: "Mirror symmetry with configurable segments",
		category: "distortion",
		params: [
			{
				key: "segments",
				type: "number",
				displayName: "Segments",
				min: 2,
				max: 32,
				step: 1,
				defaultValue: 6,
			},
			{
				key: "rotation",
				type: "number",
				displayName: "Rotation",
				min: 0,
				max: 360,
				step: 1,
				defaultValue: 0,
			},
			{
				key: "zoom",
				type: "number",
				displayName: "Zoom",
				min: 0.5,
				max: 3,
				step: 0.1,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "kaleidoscope", segments: 6, rotation: 0, zoom: 1 },
	},
	duotone: {
		type: "duotone",
		displayName: "Duotone",
		description: "Two-tone color mapping based on luminance",
		category: "color",
		params: [
			{
				key: "color_dark",
				type: "color",
				displayName: "Dark Color",
				defaultValue: "#0d0d33ff",
			},
			{
				key: "color_light",
				type: "color",
				displayName: "Light Color",
				defaultValue: "#ffcc80ff",
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "duotone", intensity: 1 },
	},
	gradientMap: {
		type: "gradientMap",
		displayName: "Gradient Map",
		description: "Map luminance through a 5-stop color gradient",
		category: "color",
		params: [
			{
				key: "color_0",
				type: "color",
				displayName: "Color 0%",
				defaultValue: "#000000ff",
			},
			{
				key: "color_25",
				type: "color",
				displayName: "Color 25%",
				defaultValue: "#000066ff",
			},
			{
				key: "color_50",
				type: "color",
				displayName: "Color 50%",
				defaultValue: "#00cc00ff",
			},
			{
				key: "color_75",
				type: "color",
				displayName: "Color 75%",
				defaultValue: "#ffff00ff",
			},
			{
				key: "color_100",
				type: "color",
				displayName: "Color 100%",
				defaultValue: "#ffffffff",
			},
			{
				key: "intensity",
				type: "number",
				displayName: "Intensity",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 1,
			},
		],
		defaultValues: { type: "gradientMap", intensity: 1 },
	},
	filmGrain: {
		type: "filmGrain",
		displayName: "Film Grain",
		description: "Photographic film grain overlay",
		category: "artistic",
		params: [
			{
				key: "grain_amount",
				type: "number",
				displayName: "Amount",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.15,
			},
			{
				key: "grain_size",
				type: "number",
				displayName: "Size",
				min: 1,
				max: 5,
				step: 0.1,
				defaultValue: 1.5,
			},
			{
				key: "luminance_response",
				type: "number",
				displayName: "Luminance Response",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.5,
			},
			{
				key: "colored",
				type: "boolean",
				displayName: "Colored Grain",
				defaultValue: false,
			},
		],
		defaultValues: {
			type: "filmGrain",
			grain_amount: 0.15,
			grain_size: 1.5,
			luminance_response: 0.5,
			colored: false,
		},
	},
	barrelDistort: {
		type: "barrelDistort",
		displayName: "Barrel Distort",
		description: "Barrel or pincushion lens distortion",
		category: "distortion",
		params: [
			{
				key: "strength",
				type: "number",
				displayName: "Strength",
				min: -1,
				max: 1,
				step: 0.05,
				defaultValue: 0.3,
			},
			{
				key: "zoom",
				type: "number",
				displayName: "Zoom",
				min: 0.5,
				max: 2,
				step: 0.05,
				defaultValue: 1,
			},
			{
				key: "chromatic",
				type: "boolean",
				displayName: "Chromatic Aberration",
				defaultValue: false,
			},
		],
		defaultValues: {
			type: "barrelDistort",
			strength: 0.3,
			zoom: 1,
			chromatic: false,
		},
	},
	mosaic: {
		type: "mosaic",
		displayName: "Mosaic",
		description: "Voronoi/stained glass mosaic effect",
		category: "artistic",
		params: [
			{
				key: "cell_size",
				type: "number",
				displayName: "Cell Size",
				min: 5,
				max: 100,
				step: 1,
				defaultValue: 20,
			},
			{
				key: "edge_width",
				type: "number",
				displayName: "Edge Width",
				min: 0,
				max: 5,
				step: 0.5,
				defaultValue: 1,
			},
			{
				key: "edge_color",
				type: "color",
				displayName: "Edge Color",
				defaultValue: "#000000ff",
			},
			{
				key: "randomness",
				type: "number",
				displayName: "Randomness",
				min: 0,
				max: 1,
				step: 0.05,
				defaultValue: 0.8,
			},
		],
		defaultValues: {
			type: "mosaic",
			cell_size: 20,
			edge_width: 1,
			randomness: 0.8,
		},
	},
};
