import type { Meta, StoryObj } from "@storybook/react";
import { PenCanvasFixture } from "../PenCanvasFixture";

const meta: Meta<typeof PenCanvasFixture> = {
	title: "Pencil/IconFont",
	component: PenCanvasFixture,
	tags: ["!autodocs"],
	parameters: {
		docs: { disable: true },
		previewTabs: { "storybook/docs/panel": { hidden: true } },
	},
};

export default meta;
type Story = StoryObj<typeof meta>;

export const MaterialCommunity: Story = {
	args: {
		document: {
			version: 1,
			children: [
				{
					id: "icon-mc-home",
					type: "icon_font",
					x: 60,
					y: 120,
					width: 60,
					height: 60,
					icon: "home",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
				{
					id: "icon-mc-heart",
					type: "icon_font",
					x: 150,
					y: 120,
					width: 60,
					height: 60,
					icon: "heart",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
				{
					id: "icon-mc-star",
					type: "icon_font",
					x: 240,
					y: 120,
					width: 60,
					height: 60,
					icon: "star",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
				{
					id: "icon-mc-camera",
					type: "icon_font",
					x: 330,
					y: 120,
					width: 60,
					height: 60,
					icon: "camera",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
				{
					id: "icon-mc-settings",
					type: "icon_font",
					x: 420,
					y: 120,
					width: 60,
					height: 60,
					icon: "settings",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
			],
		},
	},
};

export const FontAwesome: Story = {
	args: {
		document: {
			version: 1,
			children: [
				{
					id: "icon-fa-home",
					type: "icon_font",
					x: 60,
					y: 120,
					width: 60,
					height: 60,
					icon: "home",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#2563eb" },
				},
				{
					id: "icon-fa-star",
					type: "icon_font",
					x: 150,
					y: 120,
					width: 60,
					height: 60,
					icon: "star",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#2563eb" },
				},
				{
					id: "icon-fa-heart",
					type: "icon_font",
					x: 240,
					y: 120,
					width: 60,
					height: 60,
					icon: "heart",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#2563eb" },
				},
				{
					id: "icon-fa-cog",
					type: "icon_font",
					x: 330,
					y: 120,
					width: 60,
					height: 60,
					icon: "cog",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#2563eb" },
				},
				{
					id: "icon-fa-bell",
					type: "icon_font",
					x: 420,
					y: 120,
					width: 60,
					height: 60,
					icon: "bell",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#2563eb" },
				},
			],
		},
	},
};

export const Ionicons: Story = {
	args: {
		document: {
			version: 1,
			children: [
				{
					id: "icon-ion-home",
					type: "icon_font",
					x: 60,
					y: 120,
					width: 60,
					height: 60,
					icon: "home",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#0d9488" },
				},
				{
					id: "icon-ion-star",
					type: "icon_font",
					x: 150,
					y: 120,
					width: 60,
					height: 60,
					icon: "star",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#0d9488" },
				},
				{
					id: "icon-ion-heart",
					type: "icon_font",
					x: 240,
					y: 120,
					width: 60,
					height: 60,
					icon: "heart",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#0d9488" },
				},
				{
					id: "icon-ion-settings",
					type: "icon_font",
					x: 330,
					y: 120,
					width: 60,
					height: 60,
					icon: "settings",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#0d9488" },
				},
				{
					id: "icon-ion-camera",
					type: "icon_font",
					x: 420,
					y: 120,
					width: 60,
					height: 60,
					icon: "camera",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#0d9488" },
				},
			],
		},
	},
};

export const Feather: Story = {
	args: {
		document: {
			version: 1,
			children: [
				{
					id: "icon-fe-home",
					type: "icon_font",
					x: 60,
					y: 120,
					width: 60,
					height: 60,
					icon: "home",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#ea580c" },
				},
				{
					id: "icon-fe-star",
					type: "icon_font",
					x: 150,
					y: 120,
					width: 60,
					height: 60,
					icon: "star",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#ea580c" },
				},
				{
					id: "icon-fe-heart",
					type: "icon_font",
					x: 240,
					y: 120,
					width: 60,
					height: 60,
					icon: "heart",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#ea580c" },
				},
				{
					id: "icon-fe-settings",
					type: "icon_font",
					x: 330,
					y: 120,
					width: 60,
					height: 60,
					icon: "settings",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#ea580c" },
				},
				{
					id: "icon-fe-camera",
					type: "icon_font",
					x: 420,
					y: 120,
					width: 60,
					height: 60,
					icon: "camera",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#ea580c" },
				},
			],
		},
	},
};

export const ColoredIcons: Story = {
	args: {
		document: {
			version: 1,
			children: [
				{
					id: "icon-colored-1",
					type: "icon_font",
					x: 60,
					y: 120,
					width: 60,
					height: 60,
					icon: "rocket",
					iconFamily: "material-community",
					fontSize: 48,
					fill: { type: "color", color: "#7c3aed" },
				},
				{
					id: "icon-colored-2",
					type: "icon_font",
					x: 150,
					y: 120,
					width: 60,
					height: 60,
					icon: "star",
					iconFamily: "font-awesome",
					fontSize: 48,
					fill: { type: "color", color: "#059669" },
				},
				{
					id: "icon-colored-3",
					type: "icon_font",
					x: 240,
					y: 120,
					width: 60,
					height: 60,
					icon: "heart",
					iconFamily: "ionicons",
					fontSize: 48,
					fill: { type: "color", color: "#dc2626" },
				},
				{
					id: "icon-colored-4",
					type: "icon_font",
					x: 330,
					y: 120,
					width: 60,
					height: 60,
					icon: "camera",
					iconFamily: "feather",
					fontSize: 48,
					fill: { type: "color", color: "#0891b2" },
				},
				{
					id: "icon-colored-5",
					type: "icon_font",
					x: 420,
					y: 120,
					width: 60,
					height: 60,
					icon: "settings",
					iconFamily: "ant-design",
					fontSize: 48,
					fill: { type: "color", color: "#ca8a04" },
				},
			],
		},
	},
};
