import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

export const slotMachineConfig: GameAssetConfig = {
  gameId: 'slotMachine',
  gameTitle: 'Fruit Slots',
  theme: 'classic casino slot machine with glossy fruits, neon lights, and golden accents',
  style: 'cartoon',
  r2Prefix: 'generated/slotMachine',
  assets: [
    {
      type: 'entity',
      id: 'cherry',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'glossy red cherries with green stem, cartoon style slot symbol',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'lemon',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'bright yellow lemon, cartoon style slot symbol with glossy surface',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'orange',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'juicy orange citrus fruit, cartoon style slot symbol with glossy texture',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'plum',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'purple plum fruit, cartoon style slot symbol with glossy surface',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'bell',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'golden liberty bell, shiny metal cartoon style slot symbol',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'bar',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'classic BAR text symbol in gold on black, cartoon style slot machine symbol',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'seven',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'lucky red number 7, glossy cartoon style slot symbol with gold outline',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'wild',
      shape: 'box',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'WILD text with sparkles and stars, golden glossy cartoon style slot symbol',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'scatter',
      shape: 'circle',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'golden star scatter symbol with sparkles, cartoon style slot machine symbol',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'casino slot machine cabinet interior, dark velvet background with neon lights, golden frame accents, luxury casino atmosphere, cartoon style, game background',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Fruit Slots',
      themeDescription: 'classic fruit slot machine theme with golden text, cherries, and casino neon lights',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
