import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/getting-started',
        'guides/entities',
        'guides/behaviors',
        'guides/effects',
        'guides/particles',
        'guides/rules',
        'guides/creating-a-game',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-basics',
    },
    {
      type: 'autogenerated',
      dirName: 'tutorial-extras',
    },
  ],
};

export default sidebars;
