export type SharedValue<T> = { value: T };
export type AnimatableValue = number | string | boolean;
export type WithSpringConfig = Record<string, unknown>;
export type AnimatedProps<T> = T;
declare const Animated: { View: any; Text: any; Image: any; ScrollView: any; FlatList: any; createAnimatedComponent: (comp: any) => any; };
export default Animated;
export declare function useSharedValue<T>(init: T): SharedValue<T>;
export declare function useAnimatedStyle(fn: () => object): object;
export declare function withTiming(value: any, config?: any): any;
export declare function withSpring(value: any, config?: any): any;
export declare function withDelay(delay: number, animation: any): any;
export declare function withRepeat(animation: any, count?: number, reverse?: boolean): any;
export declare function withSequence(...animations: any[]): any;
export declare function runOnJS<T extends (...args: any[]) => any>(fn: T): T;
export declare function runOnUI<T extends (...args: any[]) => any>(fn: T): T;
export declare function cancelAnimation(value: any): void;
export declare function interpolate(value: number, inputRange: number[], outputRange: number[], extrapolation?: any): number;
export declare function createAnimatedComponent(comp: any): any;
export declare const Easing: Record<string, any>;
export declare const Extrapolation: { CLAMP: string; EXTEND: string; IDENTITY: string };
export declare const FadeIn: any; export declare const FadeInDown: any; export declare const FadeOut: any;
export declare const SlideInDown: any; export declare const ZoomIn: any; export declare const ZoomOut: any;
export declare const Layout: any; export declare const LinearTransition: any;
