const noop = () => {};
const identity = (v) => v;
const identity2 = (_, v) => v;
const Animated = { View: "Animated.View", Text: "Animated.Text", Image: "Animated.Image", ScrollView: "Animated.ScrollView", FlatList: "Animated.FlatList", createAnimatedComponent: (comp) => comp };
export default Animated;
export const useSharedValue = (init) => ({ value: init });
export const useAnimatedStyle = (_fn) => ({});
export const useAnimatedReaction = noop;
export const useDerivedValue = (fn) => ({ value: fn() });
export const useAnimatedScrollHandler = () => noop;
export const useAnimatedRef = () => ({ current: null });
export const useAnimatedProps = (_fn) => ({});
export const withTiming = identity;
export const withSpring = identity;
export const withDelay = identity2;
export const withRepeat = identity;
export const withSequence = (...vals) => vals[vals.length - 1];
export const withDecay = identity;
export const runOnJS = (fn) => fn;
export const runOnUI = (fn) => fn;
export const cancelAnimation = noop;
export const interpolate = (val) => val;
export const getAnimatedStyle = () => ({});
export const createAnimatedComponent = (comp) => comp;
export const measure = noop;
export const scrollTo = noop;
export const Easing = { linear: identity, ease: identity, bezier: () => identity, in: identity, out: identity, inOut: identity, circle: identity, exp: identity, elastic: () => identity, back: () => identity, bounce: identity, poly: () => identity };
export const Extrapolation = { CLAMP: "clamp", EXTEND: "extend", IDENTITY: "identity" };
const makeAnimation = () => { const self = { duration() { return self; }, delay() { return self; }, easing() { return self; }, springify() { return self; }, damping() { return self; }, stiffness() { return self; }, withInitialValues() { return self; }, build: () => noop }; return self; };
export const FadeIn = makeAnimation(); export const FadeInDown = makeAnimation(); export const FadeInUp = makeAnimation();
export const FadeInLeft = makeAnimation(); export const FadeInRight = makeAnimation();
export const FadeOut = makeAnimation(); export const FadeOutDown = makeAnimation(); export const FadeOutUp = makeAnimation();
export const SlideInDown = makeAnimation(); export const SlideInUp = makeAnimation();
export const SlideInLeft = makeAnimation(); export const SlideInRight = makeAnimation();
export const SlideOutDown = makeAnimation(); export const SlideOutUp = makeAnimation();
export const ZoomIn = makeAnimation(); export const ZoomOut = makeAnimation();
export const ZoomInDown = makeAnimation(); export const ZoomOutDown = makeAnimation();
export const Layout = makeAnimation(); export const LinearTransition = makeAnimation();
export const BounceIn = makeAnimation(); export const BounceOut = makeAnimation();
export const FlipInEasyX = makeAnimation(); export const FlipOutEasyX = makeAnimation();
export const StretchInX = makeAnimation(); export const StretchOutX = makeAnimation();
