import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const monsterBuilderConfig: GameAssetConfig = {
  gameId: 'monster-builder',
  gameTitle: 'Monster Builder',
  theme: 'fun monster creation, purple alien parts, playful building game',
  style: 'cartoon',
  r2Prefix: 'generated/monster-builder',
  assets: [
    {
      type: 'entity',
      id: 'body',
      shape: 'box',
      width: 3,
      height: 2,
      entityType: 'character',
      description: 'a large purple monster body with friendly appearance',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'head',
      shape: 'circle',
      width: 1.6,
      height: 1.6,
      entityType: 'item',
      description: 'a purple monster head with cute eyes',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'arm',
      shape: 'box',
      width: 1.2,
      height: 0.4,
      entityType: 'item',
      description: 'a purple monster arm attachment',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'leg',
      shape: 'box',
      width: 0.5,
      height: 1,
      entityType: 'item',
      description: 'a purple monster leg attachment',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A fun monster building workshop background. Dark purple space with floating monster parts. Playful and creative atmosphere. Cartoon style.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Monster Builder',
      themeDescription: 'Monster parts theme, purple alien aesthetic, fun and creative building',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
