import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const pendulumSwingConfig: GameAssetConfig = {
  gameId: 'pendulum-swing',
  gameTitle: 'Pendulum Swing',
  theme: 'jungle adventure, swinging ropes, spike pit danger',
  style: 'cartoon',
  r2Prefix: 'generated/pendulum-swing',
  assets: [
    {
      type: 'entity',
      id: 'player',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'character',
      description: 'a teal cyan character ball ready to swing',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'anchor',
      shape: 'circle',
      width: 0.5,
      height: 0.5,
      entityType: 'item',
      description: 'a gray metal anchor point for ropes',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'swingBall',
      shape: 'circle',
      width: 1.0,
      height: 1.0,
      entityType: 'item',
      description: 'an orange swinging ball pendulum',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'platform',
      shape: 'box',
      width: 2,
      height: 0.4,
      entityType: 'platform',
      description: 'a stone platform for standing',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'goal',
      shape: 'box',
      width: 0.5,
      height: 2,
      entityType: 'item',
      description: 'a green glowing goal flag to reach',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'coin',
      shape: 'circle',
      width: 0.6,
      height: 0.6,
      entityType: 'item',
      description: 'a golden shiny collectible coin',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A jungle adventure background with cave atmosphere. Dark tones with natural rock textures. Swinging ropes and platforms visible. Adventure game style.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Pendulum Swing',
      themeDescription: 'Jungle adventure theme, swinging mechanics, spike danger and gold coins',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
