import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const physicsStackerConfig: GameAssetConfig = {
  gameId: 'physics-stacker',
  gameTitle: 'Block Stacker',
  theme: "wooden toy blocks, natural wood grain, children's toy aesthetic",
  style: 'cartoon',
  r2Prefix: 'generated/physics-stacker',
  assets: [
    {
      type: 'entity',
      id: 'foundation',
      shape: 'box',
      width: 4.0,
      height: 0.6,
      entityType: 'platform',
      description: 'a sturdy wooden table or shelf that blocks rest on',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'dropper',
      shape: 'box',
      width: 2.0,
      height: 0.3,
      entityType: 'ui',
      description: "a cartoon child's hand reaching down, palm facing down, fingers slightly curled as if about to drop something",
    } as EntitySpec,
    {
      type: 'entity',
      id: 'blockWide',
      shape: 'box',
      width: 1.8,
      height: 0.6,
      entityType: 'item',
      description: 'a wide rectangular wooden toy block with rounded edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'blockMedium',
      shape: 'box',
      width: 1.4,
      height: 0.6,
      entityType: 'item',
      description: 'a medium rectangular wooden toy block with rounded edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'blockSmall',
      shape: 'box',
      width: 1.0,
      height: 0.6,
      entityType: 'item',
      description: 'a small square-ish wooden toy block with rounded edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'blockTall',
      shape: 'box',
      width: 0.6,
      height: 1.2,
      entityType: 'item',
      description: 'a tall vertical wooden toy block like a pillar or column',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: "A cozy children's playroom background for a video game. Soft bokeh blur effect, out of focus. Warm pastel colors, gentle lighting. Wooden floor, soft toys and building blocks visible but blurry. Cartoon style, cheerful atmosphere.",
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Block Stacker',
      themeDescription: "Wooden toy block style letters, colorful and cheerful, children's game aesthetic, fun and inviting",
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
