import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const pinballLiteConfig: GameAssetConfig = {
  gameId: 'pinball-lite',
  gameTitle: 'Pinball Lite',
  theme: 'classic arcade pinball, glowing neon elements, retro gaming',
  style: 'cartoon',
  r2Prefix: 'generated/pinball-lite',
  assets: [
    {
      type: 'entity',
      id: 'pinball',
      shape: 'circle',
      width: 0.6,
      height: 0.6,
      entityType: 'item',
      description: 'a silver metallic pinball with shine and reflection',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'bumper',
      shape: 'circle',
      width: 1.2,
      height: 1.2,
      entityType: 'item',
      description: 'a purple neon bumper that bounces the ball with glowing effect',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'smallBumper',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'item',
      description: 'a pink neon small bumper for extra points',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'target',
      shape: 'box',
      width: 0.8,
      height: 0.3,
      entityType: 'item',
      description: 'a green neon target indicator',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'flipper',
      shape: 'box',
      width: 1.5,
      height: 0.3,
      entityType: 'ui',
      description: 'a red flipper paddle for hitting the ball',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A classic arcade pinball table background. Deep blue-purple space with stars and neon lights. Retro gaming aesthetic with glowing elements. Cartoon style.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Pinball Lite',
      themeDescription: 'Classic pinball neon aesthetic, retro arcade, purple and green glowing elements',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
