import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const simplePlatformerConfig: GameAssetConfig = {
  gameId: 'simple-platformer',
  gameTitle: 'Simple Platformer',
  theme: 'colorful sky adventure, classic platforming, coin collecting',
  style: 'cartoon',
  r2Prefix: 'generated/simple-platformer',
  assets: [
    {
      type: 'entity',
      id: 'player',
      shape: 'box',
      width: 0.7,
      height: 1,
      entityType: 'character',
      description: 'a teal cyan character ready for adventure',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'platform',
      shape: 'box',
      width: 3,
      height: 0.5,
      entityType: 'platform',
      description: 'a white cloud-like platform for standing',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'smallPlatform',
      shape: 'box',
      width: 2,
      height: 0.4,
      entityType: 'platform',
      description: 'a smaller white cloud platform',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'coin',
      shape: 'circle',
      width: 0.6,
      height: 0.6,
      entityType: 'item',
      description: 'a golden shiny collectible coin',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'enemy',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'character',
      description: 'a red enemy patrolling the platforms',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'goal',
      shape: 'box',
      width: 0.5,
      height: 2,
      entityType: 'item',
      description: 'a green goal flag to reach the end',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A bright blue sky with fluffy white clouds. Classic platformer background with sunny atmosphere. Endless blue sky with soft clouds. Cartoon style.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Simple Platformer',
      themeDescription: 'Blue sky and cloud platforms, coin collecting adventure, classic platformer aesthetic',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
