import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const slingshotDestructionConfig: GameAssetConfig = {
  gameId: 'slingshot-destruction',
  gameTitle: 'Slingshot Destruction',
  theme: 'angry birds style destruction, wooden structures, physics puzzle',
  style: 'cartoon',
  r2Prefix: 'generated/slingshot-destruction',
  assets: [
    {
      type: 'entity',
      id: 'projectile',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'item',
      description: 'a red Angry Birds style projectile ball',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'woodBlock',
      shape: 'box',
      width: 1,
      height: 0.3,
      entityType: 'item',
      description: 'a brown wooden plank for building structures',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'stoneBlock',
      shape: 'box',
      width: 1,
      height: 0.3,
      entityType: 'item',
      description: 'a gray stone block stronger than wood',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tallWood',
      shape: 'box',
      width: 0.3,
      height: 1.2,
      entityType: 'item',
      description: 'a tall thin brown wooden post',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'target',
      shape: 'circle',
      width: 1.0,
      height: 1.0,
      entityType: 'item',
      description: 'a light green target enemy to destroy',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A peaceful countryside physics puzzle background. Green rolling hills in distance, blue sky above. Destruction game setting. Cartoon style.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Slingshot Destruction',
      themeDescription: 'Angry Birds style destruction, wooden structures, green enemy targets',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
