import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

const PEG_RADIUS = 0.125;
const BALL_RADIUS = 0.15;

export const slopeggleConfig: GameAssetConfig = {
  gameId: 'slopeggle',
  gameTitle: 'Slopeggle',
  theme: 'whimsical pachinko arcade, glowing neon, magical sparkles',
  style: 'cartoon',
  r2Prefix: 'generated/slopeggle',
  assets: [
    {
      type: 'entity',
      id: 'ball',
      shape: 'circle',
      width: BALL_RADIUS * 2,
      height: BALL_RADIUS * 2,
      entityType: 'item',
      description: 'a shiny chrome pinball with reflective highlights',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'bluePeg',
      shape: 'circle',
      width: PEG_RADIUS * 2,
      height: PEG_RADIUS * 2,
      entityType: 'item',
      description: 'a glowing blue orb peg with inner light, like a magical gem',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'orangePeg',
      shape: 'circle',
      width: PEG_RADIUS * 2,
      height: PEG_RADIUS * 2,
      entityType: 'item',
      description: 'a glowing orange orb peg with fiery inner light, like a magical gem',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'cannon',
      shape: 'box',
      width: 0.6,
      height: 0.25,
      entityType: 'ui',
      description: 'a sleek futuristic ball launcher cannon, metallic with neon accents',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'cannonBase',
      shape: 'circle',
      width: 0.6,
      height: 0.6,
      entityType: 'ui',
      description: 'a circular metallic base for a cannon, with tech details',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'bucket',
      shape: 'box',
      width: 1.2,
      height: 0.35,
      entityType: 'item',
      description: 'a glowing green catch bucket that slides back and forth, arcade style',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'portalA',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'item',
      description: 'a swirling cyan portal vortex with magical energy',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'portalB',
      shape: 'circle',
      width: 0.8,
      height: 0.8,
      entityType: 'item',
      description: 'a swirling cyan portal vortex with magical energy',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A magical arcade game background for a pachinko-style video game. Deep blue cosmic space with stars and nebula. Soft glowing particles and magical sparkles. Neon accents in blue and purple. Dreamy, ethereal atmosphere.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Slopeggle',
      themeDescription: 'Neon glow effects, arcade game aesthetic, magical sparkles and stars, deep blue and purple gradient',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
