import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../src/ai/pipeline/types';

export const tictactoeConfig: GameAssetConfig = {
  gameId: 'tictactoe',
  gameTitle: 'Tic Tac Toe',
  theme: 'classic tic-tac-toe, clean and modern arcade style',
  style: 'cartoon',
  r2Prefix: 'generated/tictactoe',
  localOutputDir: 'api/debug-output/tictactoe',
  assets: [
    {
      type: 'entity',
      id: 'piece_x',
      shape: 'box',
      width: 1,
      height: 1,
      entityType: 'item',
      description: 'cartoon penis shape, phallic symbol, cute cartoon style, pink flesh color, simple clean design, funny game piece',
      color: '#FF69B4',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'piece_o',
      shape: 'circle',
      width: 1,
      height: 1,
      entityType: 'item',
      description: 'cartoon butt shape, round bottom cheeks, cute cartoon style, peach skin color, simple clean design, funny game piece',
      color: '#FFDAB9',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'board',
      shape: 'box',
      width: 5.2,
      height: 5.2,
      entityType: 'background',
      description: 'tic-tac-toe game board, 3x3 grid with white lines forming nine squares, dark background, clean arcade style, empty cells ready for X and O pieces',
      color: '#2a2a4a',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'dark blue arcade background, subtle gradient, modern game aesthetic, empty space for game board',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Tic Tac Toe',
      themeDescription: 'tic-tac-toe title card, bold retro arcade text, X and O symbols, vibrant colors',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
