import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const TILE_SIZE = 1.6;

export const stackMatchConfig: GameAssetConfig = {
  gameId: 'stackMatch',
  gameTitle: 'Stack & Match',
  theme: 'magical garden with glowing flowers, mystical forest, fairy tale aesthetic',
  style: 'cartoon',
  r2Prefix: 'generated/stackMatch',
  assets: [
    {
      type: 'entity',
      id: 'gridSlot',
      shape: 'box',
      width: TILE_SIZE,
      height: TILE_SIZE,
      entityType: 'platform',
      description: 'a mossy stone pedestal with ancient runes carved into the surface, covered in soft green moss and tiny glowing mushrooms',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile0',
      shape: 'box',
      width: TILE_SIZE * 0.9,
      height: TILE_SIZE * 0.9,
      entityType: 'item',
      description: 'a brilliant ruby gemstone with inner fire glow, faceted crystal with magical red sparkles emanating from within',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile1',
      shape: 'box',
      width: TILE_SIZE * 0.9,
      height: TILE_SIZE * 0.9,
      entityType: 'item',
      description: 'a radiant sapphire crystal with swirling blue energy inside, faceted gem with ethereal blue glow',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile2',
      shape: 'box',
      width: TILE_SIZE * 0.9,
      height: TILE_SIZE * 0.9,
      entityType: 'item',
      description: 'a luminous emerald gemstone with nature magic swirling inside, faceted crystal with verdant green sparkles',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile3',
      shape: 'box',
      width: TILE_SIZE * 0.9,
      height: TILE_SIZE * 0.9,
      entityType: 'item',
      description: 'a golden topaz crystal radiating warm sunlight energy, faceted gem with honey-colored magical glow',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile4',
      shape: 'box',
      width: TILE_SIZE * 0.9,
      height: TILE_SIZE * 0.9,
      entityType: 'item',
      description: 'a mystical amethyst gemstone with purple arcane energy swirling within, faceted crystal with violet magical sparkles',
      color: '#8E24AA',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedTile0',
      shape: 'box',
      width: TILE_SIZE * 0.85,
      height: TILE_SIZE * 0.85,
      entityType: 'item',
      description: 'a brilliant ruby gemstone seated on a pedestal, glowing with inner fire, slightly smaller and more refined',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedTile1',
      shape: 'box',
      width: TILE_SIZE * 0.85,
      height: TILE_SIZE * 0.85,
      entityType: 'item',
      description: 'a radiant sapphire crystal seated on a pedestal, swirling with blue energy, slightly smaller and more refined',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedTile2',
      shape: 'box',
      width: TILE_SIZE * 0.85,
      height: TILE_SIZE * 0.85,
      entityType: 'item',
      description: 'a luminous emerald gemstone seated on a pedestal, pulsing with nature magic, slightly smaller and more refined',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedTile3',
      shape: 'box',
      width: TILE_SIZE * 0.85,
      height: TILE_SIZE * 0.85,
      entityType: 'item',
      description: 'a golden topaz crystal seated on a pedestal, radiating warm light, slightly smaller and more refined',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedTile4',
      shape: 'box',
      width: TILE_SIZE * 0.85,
      height: TILE_SIZE * 0.85,
      entityType: 'item',
      description: 'a mystical amethyst gemstone seated on a pedestal, swirling with arcane energy, slightly smaller and more refined',
      color: '#8E24AA',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'An enchanted forest clearing at twilight for a puzzle game. Ancient moss-covered stone pedestals arranged in a mystical pattern. Glowing fireflies floating in the air. Magical flowers with bioluminescent petals. Soft purple and blue ambient lighting filtering through towering trees. Fairy tale atmosphere with sparkles and magical particles. Deep forest greens and mystical purples.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Stack & Match',
      themeDescription: 'Enchanted garden aesthetic with glowing gemstones, magical sparkles, mystical forest vibes, fairy tale typography with vine and flower accents, deep greens and magical purples',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
