import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const BLOCK_SIZE = 1.4;

export const blockDropConfig: GameAssetConfig = {
  gameId: 'blockDrop',
  gameTitle: 'Block Drop',
  theme: 'retro 80s arcade, neon lights, synthwave, glowing grid lines',
  style: 'cartoon',
  r2Prefix: 'generated/blockDrop',
  assets: [
    {
      type: 'entity',
      id: 'columnHeader',
      shape: 'box',
      width: BLOCK_SIZE,
      height: 0.8,
      entityType: 'ui',
      description: 'a neon-lit column indicator with glowing cyan edges, dark metallic surface with pulsing light strips, arcade machine aesthetic',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'gridSlot',
      shape: 'box',
      width: BLOCK_SIZE,
      height: BLOCK_SIZE,
      entityType: 'platform',
      description: 'a dark grid cell with subtle neon purple outline, matte black surface with faint glowing grid lines at the edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'block0',
      shape: 'box',
      width: BLOCK_SIZE * 0.9,
      height: BLOCK_SIZE * 0.9,
      entityType: 'item',
      description: 'a glowing neon red cube with bright edges and inner light, synthwave style with hot pink and red gradient, pulsing energy',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'block1',
      shape: 'box',
      width: BLOCK_SIZE * 0.9,
      height: BLOCK_SIZE * 0.9,
      entityType: 'item',
      description: 'a glowing neon blue cube with electric cyan edges, synthwave style with deep blue core and bright cyan outline, pulsing energy',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'block2',
      shape: 'box',
      width: BLOCK_SIZE * 0.9,
      height: BLOCK_SIZE * 0.9,
      entityType: 'item',
      description: 'a glowing neon green cube with lime-colored edges, synthwave style with emerald core and bright green outline, pulsing energy',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'block3',
      shape: 'box',
      width: BLOCK_SIZE * 0.9,
      height: BLOCK_SIZE * 0.9,
      entityType: 'item',
      description: 'a glowing neon yellow cube with golden edges, synthwave style with amber core and bright yellow outline, pulsing energy',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedBlock0',
      shape: 'box',
      width: BLOCK_SIZE * 0.85,
      height: BLOCK_SIZE * 0.85,
      entityType: 'item',
      description: 'a settled neon red cube with dimmer glow, locked into the grid with subtle pulsing red light',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedBlock1',
      shape: 'box',
      width: BLOCK_SIZE * 0.85,
      height: BLOCK_SIZE * 0.85,
      entityType: 'item',
      description: 'a settled neon blue cube with dimmer glow, locked into the grid with subtle pulsing cyan light',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedBlock2',
      shape: 'box',
      width: BLOCK_SIZE * 0.85,
      height: BLOCK_SIZE * 0.85,
      entityType: 'item',
      description: 'a settled neon green cube with dimmer glow, locked into the grid with subtle pulsing green light',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'placedBlock3',
      shape: 'box',
      width: BLOCK_SIZE * 0.85,
      height: BLOCK_SIZE * 0.85,
      entityType: 'item',
      description: 'a settled neon yellow cube with dimmer glow, locked into the grid with subtle pulsing yellow light',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A retro 80s arcade game background with synthwave aesthetic. Dark purple and black space with neon grid lines extending to the horizon. Glowing pink and cyan neon signs in the distance. Starfield with colorful nebula. Arcade cabinet silhouettes on the sides. Laser beams and light trails. Vaporwave sunset colors at the horizon. Dark atmosphere with vibrant neon accents.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Block Drop',
      themeDescription: 'Retro 80s arcade neon style, glowing chrome text with pink and cyan gradients, synthwave grid lines, starfield background, electric glow effects and light trails',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
