import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const CELL_SIZE = 1.8;

export const game2048Config: GameAssetConfig = {
  gameId: 'game2048',
  gameTitle: '2048',
  theme: 'ancient stone tablets, mystical runes, archaeological discovery, desert temple',
  style: 'cartoon',
  r2Prefix: 'generated/game2048',
  assets: [
    {
      type: 'entity',
      id: 'emptyCell',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'platform',
      description: 'an empty stone tile slot carved into ancient temple floor, weathered sandstone with subtle hieroglyphic border, slightly recessed with worn edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile2',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a simple glowing rune for number 2, pale sandstone with faint magical glow, basic single-stroke rune symbol, subtle golden shimmer',
      color: '#eee4da',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile4',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 4, warm sandstone with soft magical glow, two-stroke rune symbol, gentle amber shimmer',
      color: '#ede0c8',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile8',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 8, orange-tinted stone with warm magical glow, three-stroke rune symbol, bright orange energy',
      color: '#f2b179',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile16',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 16, deep orange stone with pulsing magical glow, complex rune symbol, fiery orange energy swirling',
      color: '#f59563',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile32',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 32, red-orange stone with intense magical glow, intricate rune symbol, flames licking the edges',
      color: '#f67c5f',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile64',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 64, crimson stone with powerful magical glow, elaborate rune symbol, fire energy emanating outward',
      color: '#f65e3b',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile128',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 128, golden stone with radiant magical glow, ornate rune symbol with decorative border, golden light rays',
      color: '#edcf72',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile256',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 256, bright gold stone with brilliant magical glow, masterwork rune symbol, golden energy particles floating',
      color: '#edcc61',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile512',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 512, pure gold stone with intense magical glow, legendary rune symbol with arcane circles, golden aura pulsing',
      color: '#edc850',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile1024',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 1024, radiant gold stone with blinding magical glow, mythical rune symbol with multiple arcane rings, divine golden energy',
      color: '#edc53f',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'tile2048',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'item',
      description: 'an ancient stone tablet with a glowing rune for number 2048, legendary golden artifact with overwhelming magical power, ultimate rune symbol with celestial patterns, blinding golden radiance and floating particles',
      color: '#edc22e',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'gridBackground',
      shape: 'box',
      width: CELL_SIZE * 4.5,
      height: CELL_SIZE * 4.5,
      entityType: 'platform',
      description: 'an ancient temple floor grid made of carved sandstone, weathered stone with hieroglyphic borders, archaeological dig site aesthetic, torch-lit warm stone texture',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'An ancient desert temple interior for a 2048 puzzle game. Massive sandstone columns with hieroglyphics. Flickering torchlight casting warm shadows. Archaeological discovery atmosphere with ancient artifacts. Stone floor with carved patterns. Mysterious runes glowing faintly on walls. Egyptian-inspired architecture with mystical elements. Warm amber and gold tones with deep shadows.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: '2048',
      themeDescription: 'Ancient temple aesthetic with mystical runes, archaeological discovery vibes, fantasy typography with hieroglyphic and stone tablet accents, warm amber and gold tones with ancient mystical energy',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
