export const Ionicons = () => null;
export const MaterialIcons = () => null;
export const FontAwesome = () => null;
export const Feather = () => null;
export const AntDesign = () => null;
export const MaterialCommunityIcons = () => null;
export const Entypo = () => null;
export const EvilIcons = () => null;
export const FontAwesome5 = () => null;
export const Foundation = () => null;
export const Octicons = () => null;
export const SimpleLineIcons = () => null;
export const Zocial = () => null;
export default { Ionicons, MaterialIcons, FontAwesome, Feather, AntDesign };
