import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const CELL_SIZE = 0.8;
const PUYO_RADIUS = CELL_SIZE / 2 - 0.02;
const PUYO_DIAMETER = PUYO_RADIUS * 2;

export const puyoPuyoConfig: GameAssetConfig = {
  gameId: 'puyoPuyo',
  gameTitle: 'Puyo Puyo',
  theme: 'cute slime creatures, bouncy jelly world, kawaii aesthetic, colorful goo',
  style: 'cartoon',
  r2Prefix: 'generated/puyoPuyo',
  assets: [
    {
      type: 'entity',
      id: 'puyo_red',
      shape: 'circle',
      width: PUYO_DIAMETER,
      height: PUYO_DIAMETER,
      entityType: 'item',
      description: 'an adorable red slime creature with a cute kawaii face, big sparkly eyes, small happy smile, bouncy jelly texture, translucent goo body with glossy highlights, blushing cheeks',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'puyo_blue',
      shape: 'circle',
      width: PUYO_DIAMETER,
      height: PUYO_DIAMETER,
      entityType: 'item',
      description: 'an adorable blue slime creature with a cute kawaii face, big sparkly eyes, small happy smile, bouncy jelly texture, translucent goo body with glossy highlights, blushing cheeks',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'puyo_green',
      shape: 'circle',
      width: PUYO_DIAMETER,
      height: PUYO_DIAMETER,
      entityType: 'item',
      description: 'an adorable green slime creature with a cute kawaii face, big sparkly eyes, small happy smile, bouncy jelly texture, translucent goo body with glossy highlights, blushing cheeks',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'puyo_yellow',
      shape: 'circle',
      width: PUYO_DIAMETER,
      height: PUYO_DIAMETER,
      entityType: 'item',
      description: 'an adorable yellow slime creature with a cute kawaii face, big sparkly eyes, small happy smile, bouncy jelly texture, translucent goo body with glossy highlights, blushing cheeks',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'puyo_garbage',
      shape: 'circle',
      width: PUYO_DIAMETER,
      height: PUYO_DIAMETER,
      entityType: 'item',
      description: 'a gray slime creature with a grumpy kawaii face, annoyed expression, small frown, bouncy jelly texture, translucent gray goo body with glossy highlights, slightly darker than colored puyos',
      color: '#757575',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'emptyCell',
      shape: 'box',
      width: CELL_SIZE,
      height: CELL_SIZE,
      entityType: 'platform',
      description: 'a bouncy jelly container cell, translucent purple-blue gel surface, soft glow, kawaii aesthetic, slightly recessed with rounded corners',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'wall',
      shape: 'box',
      width: 0.3,
      height: CELL_SIZE * 12,
      entityType: 'platform',
      description: 'a bouncy jelly wall barrier, translucent purple gel with sparkles, soft glow, kawaii aesthetic, smooth rounded edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'wallBottom',
      shape: 'box',
      width: CELL_SIZE * 6 + 0.6,
      height: 0.3,
      entityType: 'platform',
      description: 'a bouncy jelly floor barrier, translucent purple gel with sparkles, soft glow, kawaii aesthetic, smooth rounded edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'gridBackground',
      shape: 'box',
      width: CELL_SIZE * 6,
      height: CELL_SIZE * 12,
      entityType: 'platform',
      description: 'a bouncy jelly game board background, translucent deep purple gel surface, soft inner glow, kawaii aesthetic, smooth texture with subtle sparkles',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A colorful slime kingdom world for a Puyo Puyo puzzle game. Bouncy jelly platforms floating in a candy-colored sky. Cute slime creatures in the background. Rainbow gel waterfalls. Kawaii aesthetic with sparkles and bubbles. Soft pastel colors with vibrant accents. Magical goo world with bouncy surfaces everywhere. Pink, purple, and blue color scheme with colorful highlights.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Puyo Puyo',
      themeDescription: 'Kawaii slime kingdom aesthetic with bouncy jelly textures, cute colorful slime creatures, bubbly playful typography with goo drips and sparkles, vibrant pastel colors with glossy highlights',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
