#!/usr/bin/env tsx
import { execSync } from "child_process";
import { createHash } from "crypto";
import {
	copyFileSync,
	existsSync,
	mkdirSync,
	readdirSync,
	readFileSync,
	rmSync,
	statSync,
	unlinkSync,
	writeFileSync,
} from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";
import { getPlatformProxy } from "wrangler";
import { GAME_IDS, loadGame } from "../src/lib/game-registry";

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_ROOT = resolve(__dirname, "..");
const R2_DIR = resolve(__dirname, "..", "..", "r2");
const APP_ROOT = resolve(__dirname, "..", "..", "app");
const R2_GAMES_DIR = join(R2_DIR, "games");
const EMBED_DIR = join(APP_ROOT, "assets", "embedded-games");
const REGISTRY_PATH = join(
	APP_ROOT,
	"lib",
	"offline",
	"embedded-games-registry.ts",
);

interface EmbeddedGameEntry {
	gameId: string;
	uuid: string;
	totalBytes: number;
}

interface BuildResult {
	id: string;
	success: boolean;
	totalBytes: number;
	hasScript: boolean;
	error?: string;
}

function copyDirRecursive(
	src: string,
	dest: string,
	excludeDirs: Set<string>,
): number {
	let totalBytes = 0;
	mkdirSync(dest, { recursive: true });

	for (const entry of readdirSync(src, { withFileTypes: true })) {
		const srcPath = join(src, entry.name);
		const destPath = join(dest, entry.name);

		if (entry.isDirectory()) {
			if (excludeDirs.has(entry.name)) continue;
			totalBytes += copyDirRecursive(srcPath, destPath, excludeDirs);
		} else {
			copyFileSync(srcPath, destPath);
			totalBytes += statSync(srcPath).size;
		}
	}

	return totalBytes;
}

function generateEmbeddedRegistry(embeddedGames: EmbeddedGameEntry[]): void {
	const definitionLines: string[] = [];
	const metadataLines: string[] = [];

	for (const game of embeddedGames) {
		definitionLines.push(
			`  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/definition.json'),`,
		);
		metadataLines.push(
			`  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/metadata.json'),`,
		);
	}

	const content = `// AUTO-GENERATED - DO NOT EDIT
// Generated by api/scripts/build-games.ts

export const EMBEDDED_MANIFEST = require('@/assets/embedded-games/manifest.json');

export const EMBEDDED_DEFINITIONS: Record<string, unknown> = {
${definitionLines.join("\n")}
};

export const EMBEDDED_METADATA: Record<string, unknown> = {
${metadataLines.join("\n")}
};
`;

	mkdirSync(dirname(REGISTRY_PATH), { recursive: true });
	writeFileSync(REGISTRY_PATH, content);
	console.log(`✓ Generated embedded-games-registry.ts`);
}

const SYSTEM_USER_ID = "00000000-0000-0000-0000-000000000001";
const SKIP_SEED = process.argv.includes("--skip-seed");
const WRANGLER_BIN = join(API_ROOT, "node_modules", ".bin", "wrangler");

function escapeSql(value: string): string {
	return value.replace(/'/g, "''");
}

function wrangler(args: string): void {
	execSync(`${WRANGLER_BIN} ${args}`, { cwd: API_ROOT, stdio: "pipe" });
}

const R2_SYNC_MANIFEST = join(API_ROOT, ".r2-sync-manifest.json");

function contentTypeForExt(ext: string): string {
	switch (ext) {
		case ".json":
			return "application/json";
		case ".png":
			return "image/png";
		case ".jpg":
		case ".jpeg":
			return "image/jpeg";
		case ".webp":
			return "image/webp";
		case ".svg":
			return "image/svg+xml";
		case ".gif":
			return "image/gif";
		default:
			return "application/octet-stream";
	}
}

function walkR2Files(
	dir: string,
	prefix: string,
	excludeDirs: Set<string>,
): Array<{ key: string; filePath: string }> {
	const files: Array<{ key: string; filePath: string }> = [];
	for (const entry of readdirSync(dir, { withFileTypes: true })) {
		if (entry.isDirectory()) {
			if (excludeDirs.has(entry.name)) continue;
			const subPrefix = prefix ? `${prefix}/${entry.name}` : entry.name;
			files.push(...walkR2Files(join(dir, entry.name), subPrefix, excludeDirs));
		} else {
			const key = prefix ? `${prefix}/${entry.name}` : entry.name;
			files.push({ key, filePath: join(dir, entry.name) });
		}
	}
	return files;
}

async function syncLocalR2(): Promise<void> {
	const proxy = await getPlatformProxy<{
		ASSETS: import("@cloudflare/workers-types").R2Bucket;
	}>();
	const r2 = proxy.env.ASSETS;

	const excludeDirs = new Set<string>();
	const files = walkR2Files(R2_DIR, "", excludeDirs);

	let oldManifest: Record<string, string> = {};
	if (existsSync(R2_SYNC_MANIFEST)) {
		oldManifest = JSON.parse(readFileSync(R2_SYNC_MANIFEST, "utf-8"));
	}

	const newManifest: Record<string, string> = {};
	let uploaded = 0;
	let skipped = 0;

	for (const { key, filePath } of files) {
		const content = readFileSync(filePath);
		const hash = createHash("md5").update(content).digest("hex");
		newManifest[key] = hash;

		if (oldManifest[key] === hash) {
			skipped++;
			continue;
		}

		const ext = filePath.substring(filePath.lastIndexOf("."));
		const ct = contentTypeForExt(ext);
		const arrayBuf = new Uint8Array(content).buffer;
		await (r2 as any).put(key, arrayBuf, { httpMetadata: { contentType: ct } });
		uploaded++;
	}

	let deleted = 0;
	for (const key of Object.keys(oldManifest)) {
		if (!newManifest[key]) {
			await (r2 as any).delete(key);
			deleted++;
		}
	}

	await proxy.dispose();

	writeFileSync(R2_SYNC_MANIFEST, JSON.stringify(newManifest, null, 2));

	const parts = [`${uploaded} uploaded`];
	if (deleted > 0) parts.push(`${deleted} deleted`);
	if (skipped > 0) parts.push(`${skipped} unchanged`);
	console.log(`✓ Synced local R2 (${parts.join(", ")})`);
}

function seedLocalD1(games: EmbeddedGameEntry[]): void {
	const now = Date.now();
	const d1StateDir = join(
		API_ROOT,
		".wrangler",
		"state",
		"v3",
		"d1",
		"miniflare-D1DatabaseObject",
	);

	// Reset D1 entirely (wrangler doesn't respect PRAGMA foreign_keys in file execution)
	// This is safe because embedded games are the source of truth
	if (existsSync(d1StateDir)) {
		rmSync(d1StateDir, { recursive: true });
	}

	// Re-create schema (includes system user: 00000000-0000-0000-0000-000000000001)
	wrangler(`d1 execute slopcade-db --local --file=schema.sql`);

	const statements: string[] = [];

	for (const game of games) {
		const metadataPath = join(R2_GAMES_DIR, game.gameId, "metadata.json");
		const metadata = JSON.parse(readFileSync(metadataPath, "utf-8"));
		const title = escapeSql(metadata.title ?? game.gameId);
		const description = escapeSql(metadata.description ?? "");

		statements.push(
			`INSERT INTO games (` +
				`id, user_id, title, description, r2_prefix, ` +
				`is_public, play_count, created_at, updated_at, base_game_id, ` +
				`validation_valid` +
				`) VALUES (` +
				`'${game.uuid}', '${SYSTEM_USER_ID}', ` +
				`'${title}', '${description}', 'games/${game.gameId}', ` +
				`1, 0, ${now}, ${now}, '${game.uuid}', ` +
				`1` +
				`);`,
		);
	}

	const tmpFile = join(API_ROOT, ".seed-local.sql");
	writeFileSync(tmpFile, statements.join("\n"));
	try {
		wrangler(`d1 execute slopcade-db --local --file=.seed-local.sql`);
	} finally {
		unlinkSync(tmpFile);
	}
}

async function seedLocal(embeddedGames: EmbeddedGameEntry[]): Promise<void> {
	if (SKIP_SEED) {
		console.log("⏭ Skipping local seed (--skip-seed)");
		return;
	}

	console.log("\nSeeding local Wrangler state...");

	try {
		seedLocalD1(embeddedGames);
		console.log(`✓ Seeded local D1 with ${embeddedGames.length} games`);
		await syncLocalR2();
	} catch (error) {
		const msg = error instanceof Error ? error.message : String(error);
		console.warn(`⚠ Local seed failed (non-fatal): ${msg}`);
		if (msg.includes("no column named") || msg.includes("SQLITE_ERROR")) {
			console.warn(
				`  Hint: Your local D1 schema may be outdated. Run: pnpm --filter @slopcade/api db:reset`,
			);
		}
	}
}

async function build(): Promise<void> {
	console.log("Building games...\n");

	if (existsSync(EMBED_DIR)) {
		rmSync(EMBED_DIR, { recursive: true });
	}
	mkdirSync(EMBED_DIR, { recursive: true });

	const results: BuildResult[] = [];
	const embeddedGames: EmbeddedGameEntry[] = [];
	const excludeDirs = new Set<string>();

	for (const id of GAME_IDS) {
		try {
			const entry = await loadGame(id);
			if (!entry) {
				results.push({
					id,
					success: false,
					error: "Failed to load game",
					totalBytes: 0,
					hasScript: false,
				});
				continue;
			}

			const definitionJson = JSON.stringify(entry.definition, null, 2);
			const gameUuid = entry.definition.metadata.id;

			// Write to r2/games/{id}/ (the local R2 mirror)
			const r2GameDir = join(R2_GAMES_DIR, id);
			mkdirSync(r2GameDir, { recursive: true });
			writeFileSync(join(r2GameDir, "definition.json"), definitionJson);

			const metadata = {
				id: gameUuid,
				slug: id,
				title: entry.title,
				description: entry.description,
				version:
					(entry.definition.metadata as { version?: string })?.version ??
					"1.0.0",
				thumbnailUrl: null,
				updatedAt: Date.now(),
			};
			writeFileSync(
				join(r2GameDir, "metadata.json"),
				JSON.stringify(metadata, null, 2),
			);

			const gameEmbedDir = join(EMBED_DIR, id);
			const assetBytes = copyDirRecursive(r2GameDir, gameEmbedDir, excludeDirs);

			const gameTotalBytes = Buffer.byteLength(definitionJson) + assetBytes;
			const hasScript =
				!!entry.definition.modules &&
				Object.keys(entry.definition.modules).length > 0;
			embeddedGames.push({
				gameId: id,
				uuid: gameUuid,
				totalBytes: gameTotalBytes,
			});
			results.push({
				id,
				success: true,
				totalBytes: gameTotalBytes,
				hasScript,
			});

			const parts = [id];
			if (hasScript) parts.push("+ script");
			console.log(`✓ ${parts.join(" | ")}`);
		} catch (error) {
			const errorMsg = error instanceof Error ? error.message : "Unknown error";
			results.push({
				id,
				success: false,
				error: errorMsg,
				totalBytes: 0,
				hasScript: false,
			});
			console.error(`✗ ${id}: ${errorMsg}`);
		}
	}

	// Write embedded manifest
	const totalBytes = embeddedGames.reduce((sum, g) => sum + g.totalBytes, 0);
	writeFileSync(
		join(EMBED_DIR, "manifest.json"),
		JSON.stringify(
			{
				version: 1,
				buildTime: new Date().toISOString(),
				totalGames: embeddedGames.length,
				totalBytes,
				games: embeddedGames,
			},
			null,
			2,
		),
	);

	generateEmbeddedRegistry(embeddedGames);

	await seedLocal(embeddedGames);

	const succeeded = results.filter((r) => r.success).length;
	const failed = results.filter((r) => !r.success).length;

	console.log(`\nBuild complete:`);
	console.log(`  Games: ${succeeded} succeeded, ${failed} failed`);
	console.log(`  Size: ${(totalBytes / 1024 / 1024).toFixed(2)} MB`);

	if (failed > 0) {
		process.exit(1);
	}
}

build()
	.then(() => {
		process.exit(0);
	})
	.catch((err) => {
		console.error("Build failed:", err);
		process.exit(1);
	});
