#!/usr/bin/env tsx
import {
  writeFileSync, readFileSync, mkdirSync, existsSync, rmSync,
  readdirSync, copyFileSync, statSync, unlinkSync,
} from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { createHash } from 'crypto';
import { build as esbuild } from 'esbuild';
import { GAME_IDS, loadGame } from '../src/lib/game-registry';

const __dirname = dirname(fileURLToPath(import.meta.url));
const API_ROOT = resolve(__dirname, '..');
const R2_DIR = resolve(__dirname, '..', '..', 'r2');
const APP_ROOT = resolve(__dirname, '..', '..', 'app');
const R2_GAMES_DIR = join(R2_DIR, 'games');
const EMBED_DIR = join(APP_ROOT, 'assets', 'embedded-games');
const REGISTRY_PATH = join(APP_ROOT, 'lib', 'offline', 'embedded-games-registry.ts');

interface PackManifest {
  version: number;
  packId: string;
  name: string;
  assets: Record<string, { file: string }>;
}

interface EmbeddedGameEntry {
  gameId: string;
  packs: Array<{ name: string; packId: string; assetCount: number }>;
  assetCount: number;
  totalBytes: number;
}

interface BuildResult {
  id: string;
  success: boolean;
  assetCount: number;
  totalBytes: number;
  hasScript: boolean;
  error?: string;
}

async function bundleGameScript(gameId: string): Promise<string | undefined> {
  const scriptPath = join(R2_GAMES_DIR, gameId, 'src', 'script.ts');
  if (!existsSync(scriptPath)) return undefined;

  try {
    const result = await esbuild({
      entryPoints: [scriptPath],
      bundle: true,
      format: 'cjs',
      platform: 'browser',
      target: 'es2020',
      write: false,
      minify: false,
      treeShaking: true,
    });

    return result.outputFiles[0].text;
  } catch (error) {
    console.error(`  ⚠ Failed to bundle script for ${gameId}:`, error);
    return undefined;
  }
}

function discoverPacks(gameId: string): Array<{ name: string; packId: string; assetCount: number }> {
  const packsDir = join(R2_GAMES_DIR, gameId, 'packs');
  if (!existsSync(packsDir)) return [];

  const packs: Array<{ name: string; packId: string; assetCount: number }> = [];
  for (const entry of readdirSync(packsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const manifestPath = join(packsDir, entry.name, 'manifest.json');
    if (!existsSync(manifestPath)) continue;

    const manifest: PackManifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
    packs.push({
      name: manifest.name,
      packId: manifest.packId,
      assetCount: Object.keys(manifest.assets).length,
    });
  }

  return packs;
}

function copyDirRecursive(src: string, dest: string, excludeDirs: Set<string>): number {
  let totalBytes = 0;
  mkdirSync(dest, { recursive: true });

  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      if (excludeDirs.has(entry.name)) continue;
      totalBytes += copyDirRecursive(srcPath, destPath, excludeDirs);
    } else {
      copyFileSync(srcPath, destPath);
      totalBytes += statSync(srcPath).size;
    }
  }

  return totalBytes;
}

function generateEmbeddedRegistry(embeddedGames: EmbeddedGameEntry[]): void {
  const definitionLines: string[] = [];
  const metadataLines: string[] = [];
  const packManifestLines: string[] = [];
  const assetLines: string[] = [];

  for (const game of embeddedGames) {
    definitionLines.push(
      `  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/definition.json'),`,
    );
    metadataLines.push(
      `  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/metadata.json'),`,
    );

    if (game.packs.length > 0) {
      const packEntries = game.packs.map(p =>
        `    '${p.name}': require('@/assets/embedded-games/${game.gameId}/packs/${p.name}/manifest.json'),`
      );
      packManifestLines.push(`  '${game.gameId}': {\n${packEntries.join('\n')}\n  },`);

      for (const pack of game.packs) {
        const manifestPath = join(EMBED_DIR, game.gameId, 'packs', pack.name, 'manifest.json');
        if (existsSync(manifestPath)) {
          const manifest: PackManifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
          for (const [, assetEntry] of Object.entries(manifest.assets)) {
            const assetFilePath = join(EMBED_DIR, game.gameId, 'packs', pack.name, assetEntry.file);
            if (!existsSync(assetFilePath)) continue;
            assetLines.push(
              `  '${game.gameId}/packs/${pack.name}/${assetEntry.file}': require('@/assets/embedded-games/${game.gameId}/packs/${pack.name}/${assetEntry.file}'),`,
            );
          }
        }
      }
    }
  }

  const content = `// AUTO-GENERATED - DO NOT EDIT
// Generated by api/scripts/build-games.ts

export const EMBEDDED_MANIFEST = require('@/assets/embedded-games/manifest.json');

export const EMBEDDED_DEFINITIONS: Record<string, unknown> = {
${definitionLines.join('\n')}
};

export const EMBEDDED_METADATA: Record<string, unknown> = {
${metadataLines.join('\n')}
};

export const EMBEDDED_PACK_MANIFESTS: Record<string, Record<string, unknown>> = {
${packManifestLines.join('\n')}
};

export const EMBEDDED_ASSETS: Record<string, number> = {
${assetLines.join('\n')}
};
`;

  mkdirSync(dirname(REGISTRY_PATH), { recursive: true });
  writeFileSync(REGISTRY_PATH, content);
  console.log(`✓ Generated embedded-games-registry.ts`);
}

const SLOPCADE_NAMESPACE = 'slopcade-game-seed';

function slugToUuid(slug: string): string {
  const hash = createHash('sha256').update(`${SLOPCADE_NAMESPACE}:${slug}`).digest('hex');
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    '4' + hash.slice(13, 16),
    ((parseInt(hash[16], 16) & 0x3) | 0x8).toString(16) + hash.slice(17, 20),
    hash.slice(20, 32),
  ].join('-');
}

const SYSTEM_USER_ID = '00000000-0000-0000-0000-000000000000';
const SKIP_SEED = process.argv.includes('--skip-seed');
const WRANGLER_BIN = join(API_ROOT, 'node_modules', '.bin', 'wrangler');

function escapeSql(value: string): string {
  return value.replace(/'/g, "''");
}

function wrangler(args: string): void {
  execSync(`${WRANGLER_BIN} ${args}`, { cwd: API_ROOT, stdio: 'pipe' });
}

const R2_SYNC_MANIFEST = join(API_ROOT, '.r2-sync-manifest.json');
const R2_BUCKET_NAME = 'slopcade-assets';

function contentTypeForExt(ext: string): string {
  switch (ext) {
    case '.json': return 'application/json';
    case '.png': return 'image/png';
    case '.jpg': case '.jpeg': return 'image/jpeg';
    case '.webp': return 'image/webp';
    case '.svg': return 'image/svg+xml';
    case '.gif': return 'image/gif';
    default: return 'application/octet-stream';
  }
}

function walkR2Files(dir: string, prefix: string, excludeDirs: Set<string>): Array<{ key: string; filePath: string }> {
  const files: Array<{ key: string; filePath: string }> = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (excludeDirs.has(entry.name)) continue;
      const subPrefix = prefix ? `${prefix}/${entry.name}` : entry.name;
      files.push(...walkR2Files(join(dir, entry.name), subPrefix, excludeDirs));
    } else {
      const key = prefix ? `${prefix}/${entry.name}` : entry.name;
      files.push({ key, filePath: join(dir, entry.name) });
    }
  }
  return files;
}

function syncLocalR2(): void {
  const excludeDirs = new Set(['src']);
  const files = walkR2Files(R2_DIR, '', excludeDirs);

  let oldManifest: Record<string, string> = {};
  if (existsSync(R2_SYNC_MANIFEST)) {
    oldManifest = JSON.parse(readFileSync(R2_SYNC_MANIFEST, 'utf-8'));
  }

  const newManifest: Record<string, string> = {};
  let uploaded = 0;
  let deleted = 0;
  let skipped = 0;

  for (const { key, filePath } of files) {
    const content = readFileSync(filePath);
    const hash = createHash('md5').update(content).digest('hex');
    newManifest[key] = hash;

    if (oldManifest[key] === hash) {
      skipped++;
      continue;
    }

    const ext = filePath.substring(filePath.lastIndexOf('.'));
    const ct = contentTypeForExt(ext);
    wrangler(`r2 object put ${R2_BUCKET_NAME}/${key} --file="${filePath}" --local --ct="${ct}"`);
    uploaded++;
  }

  for (const key of Object.keys(oldManifest)) {
    if (!newManifest[key]) {
      wrangler(`r2 object delete ${R2_BUCKET_NAME}/${key} --local`);
      deleted++;
    }
  }

  writeFileSync(R2_SYNC_MANIFEST, JSON.stringify(newManifest, null, 2));

  const parts = [`${uploaded} uploaded`];
  if (deleted > 0) parts.push(`${deleted} deleted`);
  if (skipped > 0) parts.push(`${skipped} unchanged`);
  console.log(`✓ Synced local R2 (${parts.join(', ')})`);
}

function seedLocalD1(games: EmbeddedGameEntry[]): void {
  const now = Date.now();
  const statements: string[] = [];

  statements.push(
    `INSERT OR IGNORE INTO users (id, email, display_name, created_at, updated_at) ` +
    `VALUES ('${SYSTEM_USER_ID}', 'system@slopcade.local', 'System', ${now}, ${now});`
  );

  statements.push(
    `PRAGMA foreign_keys = OFF;`,
    `DELETE FROM games WHERE user_id = '${SYSTEM_USER_ID}';`,
    `PRAGMA foreign_keys = ON;`,
  );

  for (const game of games) {
    const gameUuid = slugToUuid(game.gameId);
    const metadataPath = join(R2_GAMES_DIR, game.gameId, 'metadata.json');
    const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));
    const title = escapeSql(metadata.title ?? game.gameId);
    const description = escapeSql(metadata.description ?? '');

    statements.push(
      `INSERT OR REPLACE INTO games (` +
      `id, user_id, title, description, r2_prefix, ` +
      `is_public, play_count, created_at, updated_at, base_game_id, ` +
      `validation_valid` +
      `) VALUES (` +
      `'${gameUuid}', '${SYSTEM_USER_ID}', ` +
      `'${title}', '${description}', 'games/${game.gameId}', ` +
      `1, 0, ${now}, ${now}, '${gameUuid}', ` +
      `1` +
      `);`
    );
  }

  wrangler(`d1 execute slopcade-db --local --file=schema.sql`);

  const tmpFile = join(API_ROOT, '.seed-local.sql');
  writeFileSync(tmpFile, statements.join('\n'));
  try {
    wrangler(`d1 execute slopcade-db --local --file=.seed-local.sql`);
  } finally {
    unlinkSync(tmpFile);
  }
}

function seedLocal(embeddedGames: EmbeddedGameEntry[]): void {
  if (SKIP_SEED) {
    console.log('⏭ Skipping local seed (--skip-seed)');
    return;
  }

  console.log('\nSeeding local Wrangler state...');

  try {
    seedLocalD1(embeddedGames);
    console.log(`✓ Seeded local D1 with ${embeddedGames.length} games`);
    syncLocalR2();
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.warn(`⚠ Local seed failed (non-fatal): ${msg}`);
    if (msg.includes('no column named') || msg.includes('SQLITE_ERROR')) {
      console.warn(`  Hint: Your local D1 schema may be outdated. Run: pnpm --filter @slopcade/api db:reset`);
    }
  }
}

async function build(): Promise<void> {
  console.log('Building games...\n');

  if (existsSync(EMBED_DIR)) {
    rmSync(EMBED_DIR, { recursive: true });
  }
  mkdirSync(EMBED_DIR, { recursive: true });

  const results: BuildResult[] = [];
  const embeddedGames: EmbeddedGameEntry[] = [];
  const excludeDirs = new Set(['src']);

  for (const id of GAME_IDS) {
    try {
      const entry = await loadGame(id);
      if (!entry) {
        results.push({ id, success: false, error: 'Failed to load game', assetCount: 0, totalBytes: 0, hasScript: false });
        continue;
      }

      const scriptCode = await bundleGameScript(id);
      if (scriptCode) {
        entry.definition.script = scriptCode;
      }

      const packs = discoverPacks(id);

      const definition = entry.definition as { assetSystem?: { activePackId?: string } };
      if (definition.assetSystem?.activePackId && packs.length > 0) {
        const activeName = definition.assetSystem.activePackId;
        const matchingPack = packs.find(p => p.name === activeName);
        if (matchingPack) {
          definition.assetSystem.activePackId = matchingPack.packId;
        }
      }

      const definitionJson = JSON.stringify(entry.definition, null, 2);

      // Write to r2/games/{id}/ (the local R2 mirror)
      const r2GameDir = join(R2_GAMES_DIR, id);
      mkdirSync(r2GameDir, { recursive: true });
      writeFileSync(join(r2GameDir, 'definition.json'), definitionJson);

      const packEntries = packs.map(p => ({ name: p.name, packId: p.packId, assetCount: p.assetCount }));
      const metadata = {
        id: entry.id,
        title: entry.title,
        description: entry.description,
        version: (entry.definition.metadata as { version?: string })?.version ?? '1.0.0',
        thumbnailUrl: null,
        packs: packEntries,
        activePackId: (definition.assetSystem?.activePackId) ?? null,
        updatedAt: Date.now(),
      };
      writeFileSync(join(r2GameDir, 'metadata.json'), JSON.stringify(metadata, null, 2));

      // Recursively copy r2/games/{id}/ → app/assets/embedded-games/{id}/ excluding src/
      const gameEmbedDir = join(EMBED_DIR, id);
      const assetBytes = copyDirRecursive(r2GameDir, gameEmbedDir, excludeDirs);
      const assetCount = packs.reduce((sum, p) => sum + p.assetCount, 0);

      const gameTotalBytes = Buffer.byteLength(definitionJson) + assetBytes;
      embeddedGames.push({ gameId: id, packs: packEntries, assetCount, totalBytes: gameTotalBytes });
      results.push({ id, success: true, assetCount, totalBytes: gameTotalBytes, hasScript: !!scriptCode });

      const parts = [id];
      if (scriptCode) parts.push('+ script');
      if (assetCount > 0) parts.push(`${assetCount} assets`);
      console.log(`✓ ${parts.join(' | ')}`);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      results.push({ id, success: false, error: errorMsg, assetCount: 0, totalBytes: 0, hasScript: false });
      console.error(`✗ ${id}: ${errorMsg}`);
    }
  }

  // Write embedded manifest
  const totalBytes = embeddedGames.reduce((sum, g) => sum + g.totalBytes, 0);
  writeFileSync(join(EMBED_DIR, 'manifest.json'), JSON.stringify({
    version: 1,
    buildTime: new Date().toISOString(),
    totalGames: embeddedGames.length,
    totalBytes,
    games: embeddedGames,
  }, null, 2));

  generateEmbeddedRegistry(embeddedGames);

  seedLocal(embeddedGames);

  const succeeded = results.filter(r => r.success).length;
  const failed = results.filter(r => !r.success).length;
  const totalAssets = results.reduce((sum, r) => sum + r.assetCount, 0);

  console.log(`\nBuild complete:`);
  console.log(`  Games: ${succeeded} succeeded, ${failed} failed`);
  console.log(`  Assets: ${totalAssets} files`);
  console.log(`  Size: ${(totalBytes / 1024 / 1024).toFixed(2)} MB`);

  if (failed > 0) {
    process.exit(1);
  }
}

build().then(() => {
  process.exit(0);
}).catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
