#!/usr/bin/env tsx
/**
 * Sync template games from JSON export into the database.
 * 
 * This script reads the test-games.json file generated by export-test-games.ts
 * and inserts/updates them in the D1 database under the system user.
 * 
 * Prerequisites:
 *   1. Run `pnpm --filter @slopcade/app tsx scripts/export-test-games.ts` first
 *   2. Ensure the system user exists: `pnpm --filter @slopcade/api tsx scripts/seed-system-user.ts`
 * 
 * Usage:
 *   pnpm --filter @slopcade/api tsx scripts/sync-templates.ts
 */

import { execSync } from 'child_process';
import { writeFileSync, unlinkSync, existsSync, readFileSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import { validateGame, getValidationReportJson } from '../src/validation/gameValidator';
import type { GameDefinition } from '@slopcade/shared';

const __dirname = fileURLToPath(new URL('.', import.meta.url));

interface TemplateGame {
  id: string;
  title: string;
  description: string;
  definition: string;
  isPublic: boolean;
}

const SYSTEM_USER_ID = '00000000-0000-0000-0000-000000000000';

async function main() {
  const jsonPath = resolve(__dirname, 'test-games.json');
  
  if (!existsSync(jsonPath)) {
    console.error('❌ test-games.json not found!');
    console.error('   Run this first: pnpm --filter @slopcade/app tsx scripts/export-test-games.ts');
    process.exit(1);
  }
  
  console.log('Loading test games from JSON...');
  const templates: TemplateGame[] = JSON.parse(readFileSync(jsonPath, 'utf-8'));
  console.log(`Found ${templates.length} template games`);
  
  const now = Date.now();
  const results: Array<{ id: string; title: string; action: string; error?: string }> = [];
  
  // Process each template and generate SQL
  let sql = `-- Sync template games\n-- Generated at ${new Date().toISOString()}\n\n`;
  
  for (const template of templates) {
    try {
      const gameDefinition = JSON.parse(template.definition) as GameDefinition;
      const validationReport = validateGame(gameDefinition);
      
      // Use INSERT OR REPLACE to handle both create and update
      sql += `INSERT OR REPLACE INTO games (
  id, user_id, title, description, definition, is_public, play_count,
  created_at, updated_at, base_game_id,
  validation_report, validation_score, validation_critical_count,
  validation_warning_count, validation_valid, validation_updated_at, validator_version
) VALUES (
  '${template.id}',
  '${SYSTEM_USER_ID}',
  '${template.title.replace(/'/g, "''")}',
  ${template.description ? `'${template.description.replace(/'/g, "''")}'` : 'NULL'},
  '${template.definition.replace(/'/g, "''")}',
  ${template.isPublic ? 1 : 0},
  0,
  ${now},
  ${now},
  '${template.id}',
  '${getValidationReportJson(validationReport).replace(/'/g, "''")}',
  ${validationReport.summary.score},
  ${validationReport.summary.criticalCount},
  ${validationReport.summary.warningCount},
  ${validationReport.valid ? 1 : 0},
  ${now},
  '${validationReport.validatorVersion}'
);\n\n`;
      
      results.push({ id: template.id, title: template.title, action: 'synced' });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : 'Unknown error';
      results.push({ id: template.id, title: template.title, action: 'error', error: errorMsg });
      console.error(`❌ Failed to process ${template.title}: ${errorMsg}`);
    }
  }
  
  const tempFile = '/tmp/sync-templates.sql';
  writeFileSync(tempFile, sql);
  
  console.log(`\nExecuting SQL to sync ${results.filter(r => r.action === 'synced').length} templates...`);
  
  try {
    const cwd = process.cwd().includes('/api') ? process.cwd() : resolve(process.cwd(), 'api');
    execSync(`npx wrangler d1 execute slopcade-db --file=${tempFile} --local`, { 
      stdio: 'inherit',
      cwd
    });
    
    console.log('\n✅ Template sync completed!');
    console.log(`   Total: ${templates.length}`);
    console.log(`   Synced: ${results.filter(r => r.action === 'synced').length}`);
    console.log(`   Errors: ${results.filter(r => r.action === 'error').length}`);
  } finally {
    unlinkSync(tempFile);
  }
}

main().catch(err => {
  console.error('Failed to sync templates:', err);
  process.exit(1);
});
