import type { GameAssetConfig, EntitySpec, BackgroundSpec, TitleHeroSpec } from '../../../src/ai/pipeline/types';

const CARD_WIDTH = 1.8;
const CARD_HEIGHT = 2.4;

export const memoryMatchConfig: GameAssetConfig = {
  gameId: 'memoryMatch',
  gameTitle: 'Memory Match',
  theme: 'mystical ancient library, magical books, arcane symbols, scholarly atmosphere',
  style: 'cartoon',
  r2Prefix: 'generated/memoryMatch',
  assets: [
    {
      type: 'entity',
      id: 'cardBack',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'an ornate leather-bound spell book with a mysterious locked clasp, aged brown leather with golden corner decorations, arcane symbols embossed on the cover, magical energy faintly glowing around the edges',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card0',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing crimson fire rune, ancient symbol burning with red magical flames, intricate border with golden filigree, parchment background',
      color: '#E53935',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card1',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing sapphire water rune, ancient symbol flowing with blue magical energy, intricate border with silver filigree, parchment background',
      color: '#1E88E5',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card2',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing emerald nature rune, ancient symbol pulsing with green life energy, intricate border with vine decorations, parchment background',
      color: '#43A047',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card3',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing golden sun rune, ancient symbol radiating warm yellow light, intricate border with sun ray decorations, parchment background',
      color: '#FDD835',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card4',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing violet arcane rune, ancient symbol swirling with purple mystical energy, intricate border with star decorations, parchment background',
      color: '#8E24AA',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card5',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing amber earth rune, ancient symbol grounded with orange earthen power, intricate border with stone decorations, parchment background',
      color: '#FB8C00',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card6',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing rose love rune, ancient symbol emanating pink heart energy, intricate border with flower decorations, parchment background',
      color: '#EC407A',
    } as EntitySpec,
    {
      type: 'entity',
      id: 'card7',
      shape: 'box',
      width: CARD_WIDTH,
      height: CARD_HEIGHT,
      entityType: 'item',
      description: 'a magical card face showing a glowing cyan wind rune, ancient symbol swirling with teal air currents, intricate border with feather decorations, parchment background',
      color: '#00ACC1',
    } as EntitySpec,
    {
      type: 'background',
      id: 'background',
      prompt: 'A grand mystical ancient library interior for a memory card game. Towering wooden bookshelves filled with leather-bound spell books reaching to a vaulted ceiling. Floating magical orbs providing soft ambient lighting in warm gold and cool blue tones. Ancient scrolls and magical artifacts scattered on ornate wooden tables. Dust motes sparkling in beams of light from arched windows. Scholarly and enchanting atmosphere with deep mahogany and midnight blue color palette.',
      width: 1024,
      height: 1024,
    } as BackgroundSpec,
    {
      type: 'title_hero',
      id: 'title_hero',
      title: 'Memory Match',
      themeDescription: 'Ancient library aesthetic with magical books, glowing runes, scholarly atmosphere, deep mahogany and midnight blue colors, golden magical sparkles, mystical typography with arcane flourishes',
      width: 1024,
      height: 512,
    } as TitleHeroSpec,
  ],
};
