import type { GameDefinition } from "@slopcade/shared";

export const cubeWorld3D: GameDefinition = {
	metadata: {
		id: "cube-world-3d",
		title: "Cube World 3D",
		version: "1.0.0",
	},
	sceneType: "3d",
	world: {
		gravity: { x: 0, y: -9.8, z: 0 },
		floor: {
			enabled: true,
			size: 20,
			color: "#4CAF50",
		},
		sky: { type: "gradient", topColor: "#4A90D9", bottomColor: "#87CEEB" },
		lighting: "bright-day",
	} as any,
	camera3d: {
		type: "perspective",
		position: { x: 0, y: 5, z: 10 },
		lookAt: { x: 0, y: 1, z: 0 },
		fov: 60,
	} as any,
	prefabs: {
		cube: {
			id: "cube",
			tags: ["cube"],
			visual: {
				type: "primitive",
				shape: "box",
				color: "#FF6B35",
				size: { x: 1, y: 1, z: 1 },
			} as any,
			physics: { bodyType: "dynamic", mass: 1 },
			collider: { shape: "box", width: 1, height: 1, depth: 1 } as any,
		} as any,
		floor: {
			id: "floor",
			tags: ["floor"],
			visual: {
				type: "primitive",
				shape: "box",
				color: "#8BC34A",
				size: { x: 20, y: 0.5, z: 20 },
			} as any,
			physics: { bodyType: "static" },
			collider: { shape: "box", width: 20, height: 0.5, depth: 20 } as any,
		} as any,
	},
	entities: [
		{
			id: "ground",
			name: "Ground",
			prefab: "floor",
			transform: {
				x: 0,
				y: -0.25,
				z: 0,
				rotationX: 0,
				rotationY: 0,
				rotationZ: 0,
				scaleX: 1,
				scaleY: 1,
				scaleZ: 1,
			},
		} as any,
		{
			id: "cube1",
			name: "Red Cube",
			prefab: "cube",
			transform: {
				x: 0,
				y: 5,
				z: 0,
				rotationX: 0,
				rotationY: 0,
				rotationZ: 0,
				scaleX: 1,
				scaleY: 1,
				scaleZ: 1,
			},
		} as any,
		{
			id: "cube2",
			name: "Blue Cube",
			prefab: "cube",
			transform: {
				x: 2,
				y: 8,
				z: 1,
				rotationX: 0,
				rotationY: 45,
				rotationZ: 0,
				scaleX: 1,
				scaleY: 1,
				scaleZ: 1,
			},
		} as any,
		{
			id: "cube3",
			name: "Green Cube",
			prefab: "cube",
			transform: {
				x: -1,
				y: 12,
				z: -1,
				rotationX: 30,
				rotationY: 0,
				rotationZ: 0,
				scaleX: 1.5,
				scaleY: 1.5,
				scaleZ: 1.5,
			},
		} as any,
	],
	variables: {
		score: 0,
	},
	modules: {},
};
