import type { GameDefinition } from "@clover/shared";

export const pendulumSwingGame: GameDefinition = {
  metadata: {
    id: "test-pendulum-swing",
    title: "Pendulum Swing",
    description: "Tests pendulum-like physics with swinging balls and chain effects",
    version: "1.0.0",
  },
  world: {
    gravity: { x: 0, y: 9.8 },
    pixelsPerMeter: 50,
    bounds: { width: 20, height: 12 },
  },
  camera: { type: "fixed", zoom: 1 },
  ui: {
    showScore: false,
    showLives: false,
    showTimer: false,
    backgroundColor: "#1a1a2e",
  },
  templates: {
    anchor: {
      id: "anchor",
      sprite: { type: "circle", radius: 0.2, color: "#6B7280" },
      physics: {
        bodyType: "static",
        shape: "circle",
        radius: 0.2,
        density: 0,
        friction: 0,
        restitution: 0,
      },
    },
    pendulumBall: {
      id: "pendulumBall",
      sprite: { type: "circle", radius: 0.5, color: "#3B82F6" },
      physics: {
        bodyType: "dynamic",
        shape: "circle",
        radius: 0.5,
        density: 2,
        friction: 0.1,
        restitution: 0.9,
      },
    },
    heavyBall: {
      id: "heavyBall",
      sprite: { type: "circle", radius: 0.6, color: "#EF4444" },
      physics: {
        bodyType: "dynamic",
        shape: "circle",
        radius: 0.6,
        density: 4,
        friction: 0.1,
        restitution: 0.9,
      },
    },
    ground: {
      id: "ground",
      sprite: { type: "rect", width: 18, height: 0.5, color: "#374151" },
      physics: {
        bodyType: "static",
        shape: "box",
        width: 18,
        height: 0.5,
        density: 0,
        friction: 0.8,
        restitution: 0.3,
      },
    },
  },
  entities: [
    { id: "ground", name: "Ground", template: "ground", transform: { x: 10, y: 11, angle: 0, scaleX: 1, scaleY: 1 } },
    {
      id: "ceiling",
      name: "Ceiling",
      transform: { x: 10, y: 1, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "rect", width: 18, height: 0.3, color: "#4B5563" },
      physics: { bodyType: "static", shape: "box", width: 18, height: 0.3, density: 0, friction: 0.5, restitution: 0.3 },
    },
    { id: "anchor-1", name: "Anchor 1", template: "anchor", transform: { x: 5, y: 2, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "anchor-2", name: "Anchor 2", template: "anchor", transform: { x: 8, y: 2, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "anchor-3", name: "Anchor 3", template: "anchor", transform: { x: 11, y: 2, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "anchor-4", name: "Anchor 4", template: "anchor", transform: { x: 14, y: 2, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-1", name: "Ball 1", template: "pendulumBall", transform: { x: 3, y: 5, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-2", name: "Ball 2", template: "pendulumBall", transform: { x: 8, y: 6, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-3", name: "Ball 3", template: "pendulumBall", transform: { x: 11, y: 5, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-4", name: "Ball 4", template: "heavyBall", transform: { x: 14, y: 4, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-5", name: "Ball 5", template: "heavyBall", transform: { x: 17, y: 3, angle: 0, scaleX: 1, scaleY: 1 } },
    {
      id: "newton-cradle-anchor",
      name: "Newton Cradle Anchor",
      transform: { x: 10, y: 2.5, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "rect", width: 4, height: 0.2, color: "#6B7280" },
      physics: { bodyType: "static", shape: "box", width: 4, height: 0.2, density: 0, friction: 0, restitution: 0 },
    },
    {
      id: "nc-ball-1",
      name: "NC Ball 1",
      transform: { x: 8.5, y: 6, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "circle", radius: 0.4, color: "#F59E0B" },
      physics: { bodyType: "dynamic", shape: "circle", radius: 0.4, density: 3, friction: 0.05, restitution: 1.0 },
    },
    {
      id: "nc-ball-2",
      name: "NC Ball 2",
      transform: { x: 9.4, y: 6, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "circle", radius: 0.4, color: "#F59E0B" },
      physics: { bodyType: "dynamic", shape: "circle", radius: 0.4, density: 3, friction: 0.05, restitution: 1.0 },
    },
    {
      id: "nc-ball-3",
      name: "NC Ball 3",
      transform: { x: 10.3, y: 6, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "circle", radius: 0.4, color: "#F59E0B" },
      physics: { bodyType: "dynamic", shape: "circle", radius: 0.4, density: 3, friction: 0.05, restitution: 1.0 },
    },
    {
      id: "nc-ball-4",
      name: "NC Ball 4",
      transform: { x: 11.2, y: 6, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "circle", radius: 0.4, color: "#F59E0B" },
      physics: { bodyType: "dynamic", shape: "circle", radius: 0.4, density: 3, friction: 0.05, restitution: 1.0 },
    },
    {
      id: "striker",
      name: "Striker Ball",
      transform: { x: 2, y: 3, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "circle", radius: 0.5, color: "#10B981" },
      physics: { bodyType: "dynamic", shape: "circle", radius: 0.5, density: 5, friction: 0.1, restitution: 0.95 },
    },
  ],
};
