import type { GameDefinition } from "@clover/shared";

export const pinballLiteGame: GameDefinition = {
  metadata: {
    id: "test-pinball-lite",
    title: "Pinball Lite",
    description: "Pinball table with bumpers, flippers, and bouncy physics",
    version: "1.0.0",
  },
  world: {
    gravity: { x: 0, y: 8 },
    pixelsPerMeter: 50,
    bounds: { width: 10, height: 16 },
  },
  camera: { type: "fixed", zoom: 1 },
  ui: {
    showScore: false,
    showLives: false,
    showTimer: false,
    backgroundColor: "#0a0a2e",
  },
  templates: {
    pinball: {
      id: "pinball",
      sprite: { type: "circle", radius: 0.3, color: "#C0C0C0" },
      physics: {
        bodyType: "dynamic",
        shape: "circle",
        radius: 0.3,
        density: 2,
        friction: 0.1,
        restitution: 0.6,
      },
    },
    bumper: {
      id: "bumper",
      sprite: { type: "circle", radius: 0.6, color: "#9b59b6" },
      physics: {
        bodyType: "static",
        shape: "circle",
        radius: 0.6,
        density: 0,
        friction: 0,
        restitution: 1.5,
      },
    },
    smallBumper: {
      id: "smallBumper",
      sprite: { type: "circle", radius: 0.4, color: "#e91e63" },
      physics: {
        bodyType: "static",
        shape: "circle",
        radius: 0.4,
        density: 0,
        friction: 0,
        restitution: 1.3,
      },
    },
    wall: {
      id: "wall",
      sprite: { type: "rect", width: 0.3, height: 16, color: "#333366" },
      physics: {
        bodyType: "static",
        shape: "box",
        width: 0.3,
        height: 16,
        density: 0,
        friction: 0.1,
        restitution: 0.5,
      },
    },
    flipper: {
      id: "flipper",
      sprite: { type: "rect", width: 1.5, height: 0.3, color: "#e74c3c" },
      physics: {
        bodyType: "dynamic",
        shape: "box",
        width: 1.5,
        height: 0.3,
        density: 1,
        friction: 0.5,
        restitution: 0.3,
      },
    },
  },
  entities: [
    { id: "wall-left", name: "Left Wall", template: "wall", transform: { x: 0.15, y: 8, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "wall-right", name: "Right Wall", template: "wall", transform: { x: 9.85, y: 8, angle: 0, scaleX: 1, scaleY: 1 } },
    {
      id: "wall-top",
      name: "Top Wall",
      transform: { x: 5, y: 0.15, angle: 0, scaleX: 1, scaleY: 1 },
      sprite: { type: "rect", width: 10, height: 0.3, color: "#333366" },
      physics: { bodyType: "static", shape: "box", width: 10, height: 0.3, density: 0, friction: 0.1, restitution: 0.5 },
    },
    { id: "bumper-1", name: "Bumper 1", template: "bumper", transform: { x: 3, y: 4, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "bumper-2", name: "Bumper 2", template: "bumper", transform: { x: 7, y: 4, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "bumper-3", name: "Bumper 3", template: "bumper", transform: { x: 5, y: 5.5, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "small-bumper-1", name: "Small Bumper 1", template: "smallBumper", transform: { x: 2, y: 7, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "small-bumper-2", name: "Small Bumper 2", template: "smallBumper", transform: { x: 8, y: 7, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "small-bumper-3", name: "Small Bumper 3", template: "smallBumper", transform: { x: 5, y: 8, angle: 0, scaleX: 1, scaleY: 1 } },
    {
      id: "slingshot-left",
      name: "Left Slingshot",
      transform: { x: 1.5, y: 11, angle: Math.PI / 6, scaleX: 1, scaleY: 1 },
      sprite: { type: "rect", width: 2, height: 0.2, color: "#f39c12" },
      physics: { bodyType: "static", shape: "box", width: 2, height: 0.2, density: 0, friction: 0, restitution: 1.2 },
    },
    {
      id: "slingshot-right",
      name: "Right Slingshot",
      transform: { x: 8.5, y: 11, angle: -Math.PI / 6, scaleX: 1, scaleY: 1 },
      sprite: { type: "rect", width: 2, height: 0.2, color: "#f39c12" },
      physics: { bodyType: "static", shape: "box", width: 2, height: 0.2, density: 0, friction: 0, restitution: 1.2 },
    },
    { id: "flipper-left", name: "Left Flipper", template: "flipper", transform: { x: 3, y: 13.5, angle: 0.3, scaleX: 1, scaleY: 1 } },
    { id: "flipper-right", name: "Right Flipper", template: "flipper", transform: { x: 7, y: 13.5, angle: -0.3, scaleX: 1, scaleY: 1 } },
    { id: "ball-1", name: "Ball 1", template: "pinball", transform: { x: 5, y: 2, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-2", name: "Ball 2", template: "pinball", transform: { x: 3, y: 1, angle: 0, scaleX: 1, scaleY: 1 } },
    { id: "ball-3", name: "Ball 3", template: "pinball", transform: { x: 7, y: 1.5, angle: 0, scaleX: 1, scaleY: 1 } },
  ],
};
