#!/usr/bin/env tsx
import { existsSync, mkdirSync, rmSync, readdirSync, copyFileSync, readFileSync, writeFileSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = join(__dirname, '..');
const GAMES_ROOT = join(APP_ROOT, '..', 'games');
const OUTPUT_DIR = join(APP_ROOT, 'assets', 'embedded-games');

interface GameManifest {
  version: number;
  buildTime: string;
  games: Array<{ id: string; file: string }>;
}

interface AssetManifestEntry {
  file: string;
  r2Key: string;
}

interface EmbeddedGameEntry {
  gameId: string;
  packId: string;
  assetCount: number;
  totalBytes: number;
}

interface EmbeddedManifest {
  version: number;
  buildTime: string;
  totalGames: number;
  totalBytes: number;
  games: EmbeddedGameEntry[];
}

function extractPackId(r2Key: string): string {
  const parts = r2Key.split('/');
  return parts.length >= 3 ? parts[2] : 'unknown';
}

function generateEmptyRegistry(): void {
  const registryPath = join(APP_ROOT, 'lib', 'offline', 'embedded-games-registry.ts');
  const registryContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by app/scripts/embed-games.ts

export const EMBEDDED_MANIFEST = { version: 1, totalGames: 0, totalBytes: 0, games: [] };
export const EMBEDDED_GAME_JSONS: Record<string, unknown> = {};
export const EMBEDDED_ASSET_MANIFESTS: Record<string, Record<string, { file: string; r2Key: string }>> = {};
export const EMBEDDED_ASSETS: Record<string, number> = {};
`;
  writeFileSync(registryPath, registryContent);
  console.log(`[embed-games] Generated empty registry: ${registryPath}`);
}

function generateAssetRegistry(games: EmbeddedGameEntry[], gamesCompiledDir: string): void {
  const registryPath = join(APP_ROOT, 'lib', 'offline', 'embedded-games-registry.ts');
  
  const assetRequires: string[] = [];
  const gameJsonRequires: string[] = [];
  const assetManifestRequires: string[] = [];
  
  for (const game of games) {
    gameJsonRequires.push(`  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/game.json'),`);
    
    if (game.assetCount > 0) {
      assetManifestRequires.push(`  '${game.gameId}': require('@/assets/embedded-games/${game.gameId}/asset-manifest.json'),`);
      
      const assetManifestPath = join(gamesCompiledDir, game.gameId, 'assets', 'manifest.json');
      if (existsSync(assetManifestPath)) {
        const assetManifest: Record<string, AssetManifestEntry> = JSON.parse(readFileSync(assetManifestPath, 'utf-8'));
        
        for (const [_templateId, entry] of Object.entries(assetManifest)) {
          const filename = entry.file.replace('assets/', '');
          assetRequires.push(`  '${game.gameId}/${filename}': require('@/assets/embedded-games/${game.gameId}/assets/${filename}'),`);
        }
      }
    }
  }
  
  const registryContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by app/scripts/embed-games.ts

export const EMBEDDED_MANIFEST = require('@/assets/embedded-games/manifest.json');

export const EMBEDDED_GAME_JSONS: Record<string, unknown> = {
${gameJsonRequires.join('\n')}
};

export const EMBEDDED_ASSET_MANIFESTS: Record<string, Record<string, { file: string; r2Key: string }>> = {
${assetManifestRequires.join('\n')}
};

export const EMBEDDED_ASSETS: Record<string, number> = {
${assetRequires.join('\n')}
};
`;
  
  writeFileSync(registryPath, registryContent);
  console.log(`[embed-games] Generated asset registry: ${registryPath}`);
}

function copyDirectoryContents(src: string, dest: string): number {
  let totalBytes = 0;
  
  if (!existsSync(dest)) {
    mkdirSync(dest, { recursive: true });
  }

  const entries = readdirSync(src, { withFileTypes: true });
  
  for (const entry of entries) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);
    
    if (entry.isDirectory()) {
      totalBytes += copyDirectoryContents(srcPath, destPath);
    } else if (entry.isFile() && entry.name.endsWith('.png')) {
      copyFileSync(srcPath, destPath);
      totalBytes += statSync(srcPath).size;
    }
  }
  
  return totalBytes;
}

async function main() {
  const embedGames = process.env.EXPO_PUBLIC_EMBED_GAMES === 'true';
  
  console.log(`[embed-games] EXPO_PUBLIC_EMBED_GAMES=${embedGames}`);
  
  if (existsSync(OUTPUT_DIR)) {
    rmSync(OUTPUT_DIR, { recursive: true });
    console.log(`[embed-games] Cleaned ${OUTPUT_DIR}`);
  }
  
  if (!embedGames) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
    const emptyManifest: EmbeddedManifest = {
      version: 1,
      buildTime: new Date().toISOString(),
      totalGames: 0,
      totalBytes: 0,
      games: [],
    };
    writeFileSync(join(OUTPUT_DIR, 'manifest.json'), JSON.stringify(emptyManifest, null, 2));
    generateEmptyRegistry();
    console.log('[embed-games] Created empty manifest (embedding disabled)');
    return;
  }
  
  const gamesDistDir = join(GAMES_ROOT, 'dist');
  const gamesCompiledDir = join(GAMES_ROOT, 'compiled');
  
  if (!existsSync(gamesDistDir)) {
    console.error(`[embed-games] ERROR: games/dist not found at ${gamesDistDir}`);
    console.error('[embed-games] Run "pnpm --filter @slopcade/games build" first');
    process.exit(1);
  }
  
  const manifestPath = join(gamesDistDir, 'manifest.json');
  if (!existsSync(manifestPath)) {
    console.error(`[embed-games] ERROR: manifest.json not found at ${manifestPath}`);
    process.exit(1);
  }
  
  const gamesManifest: GameManifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  
  mkdirSync(OUTPUT_DIR, { recursive: true });
  
  const embeddedGames: EmbeddedGameEntry[] = [];
  let totalBytes = 0;
  
  for (const game of gamesManifest.games) {
    const gameId = game.id;
    console.log(`[embed-games] Processing ${gameId}...`);
    
    const gameOutputDir = join(OUTPUT_DIR, gameId);
    mkdirSync(gameOutputDir, { recursive: true });
    
    const gameJsonPath = join(gamesDistDir, game.file);
    if (!existsSync(gameJsonPath)) {
      console.warn(`[embed-games] WARNING: ${game.file} not found, skipping`);
      continue;
    }
    
    const gameJson = readFileSync(gameJsonPath, 'utf-8');
    writeFileSync(join(gameOutputDir, 'game.json'), gameJson);
    const gameJsonBytes = Buffer.byteLength(gameJson);
    
    const assetManifestPath = join(gamesCompiledDir, gameId, 'assets', 'manifest.json');
    let packId = 'embedded';
    let assetCount = 0;
    let assetBytes = 0;
    
    if (existsSync(assetManifestPath)) {
      const assetManifestJson = readFileSync(assetManifestPath, 'utf-8');
      const assetManifest: Record<string, AssetManifestEntry> = JSON.parse(assetManifestJson);
      
      writeFileSync(join(gameOutputDir, 'asset-manifest.json'), assetManifestJson);
      
      const firstEntry = Object.values(assetManifest)[0];
      if (firstEntry) {
        packId = extractPackId(firstEntry.r2Key);
      }
      
      const assetsDir = join(gamesCompiledDir, gameId, 'assets');
      const assetsOutputDir = join(gameOutputDir, 'assets');
      
      if (existsSync(assetsDir)) {
        assetBytes = copyDirectoryContents(assetsDir, assetsOutputDir);
        assetCount = Object.keys(assetManifest).length;
      }
    } else {
      console.log(`[embed-games]   No asset manifest found for ${gameId}`);
    }
    
    const gameTotalBytes = gameJsonBytes + assetBytes;
    totalBytes += gameTotalBytes;
    
    embeddedGames.push({
      gameId,
      packId,
      assetCount,
      totalBytes: gameTotalBytes,
    });
    
    console.log(`[embed-games]   ${gameId}: ${assetCount} assets, ${(gameTotalBytes / 1024).toFixed(1)} KB`);
  }
  
  const embeddedManifest: EmbeddedManifest = {
    version: 1,
    buildTime: new Date().toISOString(),
    totalGames: embeddedGames.length,
    totalBytes,
    games: embeddedGames,
  };
  
  writeFileSync(join(OUTPUT_DIR, 'manifest.json'), JSON.stringify(embeddedManifest, null, 2));
  
  generateAssetRegistry(embeddedGames, gamesCompiledDir);
  
  console.log(`\n[embed-games] Complete!`);
  console.log(`[embed-games]   Games: ${embeddedGames.length}`);
  console.log(`[embed-games]   Total size: ${(totalBytes / 1024 / 1024).toFixed(2)} MB`);
  console.log(`[embed-games]   Output: ${OUTPUT_DIR}`);
}

main().catch(err => {
  console.error('[embed-games] Fatal error:', err);
  process.exit(1);
});
