name = "slopcade-api"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "enable_nodejs_fs_module"]
main = "src/index.ts"
workers_dev = true

[define]
__DEV__ = "true"

[vars]
REQUIRE_INVITE = "true"

[dev]
port = 8789

[[d1_databases]]
binding = "DB"
database_name = "slopcade-db"
database_id = "2f549a62-08dc-41fb-8222-a211b6cdff3d"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "slopcade-assets"
preview_bucket_name = "slopcade-assets-dev"

[[durable_objects.bindings]]
name = "REALTIME_RELAY"
class_name = "RealtimeRelayDO"

[[durable_objects.bindings]]
name = "GAME_REPO"
class_name = "GameRepoDO"

[[durable_objects.bindings]]
name = "PARTY_ROOM"
class_name = "PartyRoomDO"

[[migrations]]
tag = "v2"
new_classes = ["RunCoordinatorDO", "RunStepWorkerDO"]

[[migrations]]
tag = "v3"
new_classes = ["RealtimeRelayDO"]

[[migrations]]
tag = "v4"
deleted_classes = ["RunCoordinatorDO", "RunStepWorkerDO"]

[[migrations]]
tag = "v5"
new_classes = ["GameRepoDO"]

[[migrations]]
tag = "v6"
new_classes = ["PartyRoomDO"]

[[routes]]
pattern = "api.slopcade.com"
custom_domain = true

[[routes]]
pattern = "api.amen.games"
custom_domain = true

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
